/*
 * Copyright (C) 2009-2016 by the geOrchestra PSC
 *
 * This file is part of geOrchestra.
 *
 * geOrchestra is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option)
 * any later version.
 *
 * geOrchestra is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * geOrchestra.  If not, see <http://www.gnu.org/licenses/>.
 */

package org.georchestra.extractorapp.ws.extractor;

import java.io.File;

import org.geotools.data.simple.SimpleFeatureCollection;
import org.opengis.feature.simple.SimpleFeatureType;
import org.opengis.util.ProgressListener;

/**
 * This class implements the MIF-format writing strategy.
 * 
 * @deprecated this format is generated by {@link OGRFeatureWriter}
 * 
 * @author Mauricio Pazos
 *
 */
class MifFeatureWriter extends FileFeatureWriter {

	/**
	 * new instance of MifFeatureWriter
	 * @param progressListerner
	 * @param schema
	 * @param basedir
	 * @param features
	 */
	public MifFeatureWriter(ProgressListener progressListerner,
			SimpleFeatureType schema,
			File basedir,
			SimpleFeatureCollection features) {
		
		super(progressListerner, schema, basedir, features);
	}

	/**
	 * Creates a {@link MifDatastoreFactory}
	 * 
	 * @return a {@link MifDatastoreFactory}
	 */
	@Override
	protected DatastoreFactory getDatastoreFactory(){
		return new MifDatastoreFactory();
	}
	
	

}
