package org.georchestra.mapfishapp.ws;

import org.georchestra.mapfishapp.model.ConnectionPool;

/**
 * This service handles the storage and the loading of a sld file on a temporary directory.
 * 
 * @author yoann buch  - yoann.buch@gmail.com
 *
 */
public class SLDDocService extends A_DocService {

    public static final String FILE_EXTENSION = ".sld";
    public static final String MIME_TYPE = "application/vnd.ogc.sld+xml";
    public static final String SCHEMA_URL = "http://schemas.opengis.net/sld/1.1.0/StyledLayerDescriptor.xsd";
    
    
    public SLDDocService(final String tempDir, ConnectionPool pgpool) {
        super(FILE_EXTENSION, MIME_TYPE, tempDir, pgpool);
    }
    
    
    /*=================================Overridden methods===============================================*/
    
    /**
     * Called before saving the content
     * @throws DocServiceException
     */
    @Override
    protected void preSave() throws DocServiceException {
        
        // check if sld content is valid towards its xsd schema
        /* disabled because SLD files generated by Classifier are not valid (problem of version)
        isDocumentValid(SCHEMA_URL);
        */
    }

}
