#!/bin/bash

# test if already initialized
if [ ! -d /etc/ldap/slapd.d ]; then

    # init ldap config
    echo -n "init with upstream entrypoint..."
    /entrypoint.sh true
    echo "OK"

    # start slapd in background
    echo -n "Start slapd daemon in background..."
    slapd -u openldap -g openldap -h "ldapi:/// ldap:///"
    echo "OK"

    echo -n "waiting for ldap deamon to start..."
    while true; do
        sleep 10
        ldapsearch -x >/dev/null 2>&1
        if [ $? -eq 0 ]; then
            break
        fi
    done;
    echo "OK"

    echo "Populating ldap tree..."
    ldapadd -D"cn=admin,dc=georchestra,dc=org" -w "secret" -f /tmp/georchestra.ldif
    echo "Populating ldap tree...OK"

    pkill slapd

    # wait for ldap to stop
    echo -n "wait for ldap to stop..."
    while true; do
        sleep 10
        pgrep slapd >/dev/null 2>&1
        if [ $? -ne 0 ]; then
            break
        fi
    done;
    echo "OK"

else
    echo "Ldap already initialised"

fi



