/*
 * GeoNetwork Api Documentation (beta)
 * Learn how to access the catalog using the GeoNetwork REST API.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.fao.geonet.openapi.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * AttributeTable
 */

public class AttributeTable {
    @JsonProperty("element")
    private List<Element> element = null;

    public AttributeTable element(List<Element> element) {
        this.element = element;
        return this;
    }

    public AttributeTable addElementItem(Element elementItem) {
        if (this.element == null) {
            this.element = new ArrayList<>();
        }
        this.element.add(elementItem);
        return this;
    }

    /**
     * Get element
     * 
     * @return element
     **/
    @ApiModelProperty(value = "")
    public List<Element> getElement() {
        return element;
    }

    public void setElement(List<Element> element) {
        this.element = element;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AttributeTable attributeTable = (AttributeTable) o;
        return Objects.equals(this.element, attributeTable.element);
    }

    @Override
    public int hashCode() {
        return Objects.hash(element);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class AttributeTable {\n");

        sb.append("    element: ").append(toIndentedString(element)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
