/*
 * GeoNetwork Api Documentation (beta)
 * Learn how to access the catalog using the GeoNetwork REST API.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.fao.geonet.openapi.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * BatchEditing
 */

public class BatchEditing {
    @JsonProperty("section")
    private List<Section> section = null;

    public BatchEditing section(List<Section> section) {
        this.section = section;
        return this;
    }

    public BatchEditing addSectionItem(Section sectionItem) {
        if (this.section == null) {
            this.section = new ArrayList<>();
        }
        this.section.add(sectionItem);
        return this;
    }

    /**
     * Get section
     * 
     * @return section
     **/
    @ApiModelProperty(value = "")
    public List<Section> getSection() {
        return section;
    }

    public void setSection(List<Section> section) {
        this.section = section;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        BatchEditing batchEditing = (BatchEditing) o;
        return Objects.equals(this.section, batchEditing.section);
    }

    @Override
    public int hashCode() {
        return Objects.hash(section);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class BatchEditing {\n");

        sb.append("    section: ").append(toIndentedString(section)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
