/*
 * GeoNetwork Api Documentation (beta)
 * Learn how to access the catalog using the GeoNetwork REST API.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.fao.geonet.openapi.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * Codelist
 */

public class Codelist {
    @JsonProperty("alias")
    private String alias = null;

    @JsonProperty("entry")
    private List<Entry> entry = null;

    @JsonProperty("name")
    private String name = null;

    public Codelist alias(String alias) {
        this.alias = alias;
        return this;
    }

    /**
     * Get alias
     * 
     * @return alias
     **/
    @ApiModelProperty(value = "")
    public String getAlias() {
        return alias;
    }

    public void setAlias(String alias) {
        this.alias = alias;
    }

    public Codelist entry(List<Entry> entry) {
        this.entry = entry;
        return this;
    }

    public Codelist addEntryItem(Entry entryItem) {
        if (this.entry == null) {
            this.entry = new ArrayList<>();
        }
        this.entry.add(entryItem);
        return this;
    }

    /**
     * Get entry
     * 
     * @return entry
     **/
    @ApiModelProperty(value = "")
    public List<Entry> getEntry() {
        return entry;
    }

    public void setEntry(List<Entry> entry) {
        this.entry = entry;
    }

    public Codelist name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get name
     * 
     * @return name
     **/
    @ApiModelProperty(value = "")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Codelist codelist = (Codelist) o;
        return Objects.equals(this.alias, codelist.alias) && Objects.equals(this.entry, codelist.entry)
                && Objects.equals(this.name, codelist.name);
    }

    @Override
    public int hashCode() {
        return Objects.hash(alias, entry, name);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Codelist {\n");

        sb.append("    alias: ").append(toIndentedString(alias)).append("\n");
        sb.append("    entry: ").append(toIndentedString(entry)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
