/*
 * GeoNetwork Api Documentation (beta)
 * Learn how to access the catalog using the GeoNetwork REST API.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.fao.geonet.openapi.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * Fcat
 */

public class Fcat {
    @JsonProperty("item")
    private List<FCRelatedMetadataItem> item = null;

    public Fcat item(List<FCRelatedMetadataItem> item) {
        this.item = item;
        return this;
    }

    public Fcat addItemItem(FCRelatedMetadataItem itemItem) {
        if (this.item == null) {
            this.item = new ArrayList<>();
        }
        this.item.add(itemItem);
        return this;
    }

    /**
     * Get item
     * 
     * @return item
     **/
    @ApiModelProperty(value = "")
    public List<FCRelatedMetadataItem> getItem() {
        return item;
    }

    public void setItem(List<FCRelatedMetadataItem> item) {
        this.item = item;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Fcat fcat = (Fcat) o;
        return Objects.equals(this.item, fcat.item);
    }

    @Override
    public int hashCode() {
        return Objects.hash(item);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Fcat {\n");

        sb.append("    item: ").append(toIndentedString(item)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
