/*
 * GeoNetwork Api Documentation (beta)
 * Learn how to access the catalog using the GeoNetwork REST API.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.fao.geonet.openapi.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * FCRelatedMetadataItem
 */

public class FCRelatedMetadataItem {
    @JsonProperty("description")
    private Description description = null;

    @JsonProperty("featureType")
    private FeatureType featureType = null;

    @JsonProperty("id")
    private String id = null;

    @JsonProperty("mdType")
    private List<String> mdType = null;

    @JsonProperty("title")
    private MultilingualValue title = null;

    @JsonProperty("type")
    private String type = null;

    @JsonProperty("url")
    private MultilingualValue url = null;

    public FCRelatedMetadataItem description(Description description) {
        this.description = description;
        return this;
    }

    /**
     * Get description
     * 
     * @return description
     **/
    @ApiModelProperty(value = "")
    public Description getDescription() {
        return description;
    }

    public void setDescription(Description description) {
        this.description = description;
    }

    public FCRelatedMetadataItem featureType(FeatureType featureType) {
        this.featureType = featureType;
        return this;
    }

    /**
     * Get featureType
     * 
     * @return featureType
     **/
    @ApiModelProperty(value = "")
    public FeatureType getFeatureType() {
        return featureType;
    }

    public void setFeatureType(FeatureType featureType) {
        this.featureType = featureType;
    }

    public FCRelatedMetadataItem id(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     * 
     * @return id
     **/
    @ApiModelProperty(value = "")
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public FCRelatedMetadataItem mdType(List<String> mdType) {
        this.mdType = mdType;
        return this;
    }

    public FCRelatedMetadataItem addMdTypeItem(String mdTypeItem) {
        if (this.mdType == null) {
            this.mdType = new ArrayList<>();
        }
        this.mdType.add(mdTypeItem);
        return this;
    }

    /**
     * Get mdType
     * 
     * @return mdType
     **/
    @ApiModelProperty(value = "")
    public List<String> getMdType() {
        return mdType;
    }

    public void setMdType(List<String> mdType) {
        this.mdType = mdType;
    }

    public FCRelatedMetadataItem title(MultilingualValue title) {
        this.title = title;
        return this;
    }

    /**
     * Get title
     * 
     * @return title
     **/
    @ApiModelProperty(value = "")
    public MultilingualValue getTitle() {
        return title;
    }

    public void setTitle(MultilingualValue title) {
        this.title = title;
    }

    public FCRelatedMetadataItem type(String type) {
        this.type = type;
        return this;
    }

    /**
     * Get type
     * 
     * @return type
     **/
    @ApiModelProperty(value = "")
    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public FCRelatedMetadataItem url(MultilingualValue url) {
        this.url = url;
        return this;
    }

    /**
     * Get url
     * 
     * @return url
     **/
    @ApiModelProperty(value = "")
    public MultilingualValue getUrl() {
        return url;
    }

    public void setUrl(MultilingualValue url) {
        this.url = url;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        FCRelatedMetadataItem fcRelatedMetadataItem = (FCRelatedMetadataItem) o;
        return Objects.equals(this.description, fcRelatedMetadataItem.description)
                && Objects.equals(this.featureType, fcRelatedMetadataItem.featureType)
                && Objects.equals(this.id, fcRelatedMetadataItem.id)
                && Objects.equals(this.mdType, fcRelatedMetadataItem.mdType)
                && Objects.equals(this.title, fcRelatedMetadataItem.title)
                && Objects.equals(this.type, fcRelatedMetadataItem.type)
                && Objects.equals(this.url, fcRelatedMetadataItem.url);
    }

    @Override
    public int hashCode() {
        return Objects.hash(description, featureType, id, mdType, title, type, url);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class FCRelatedMetadataItem {\n");

        sb.append("    description: ").append(toIndentedString(description)).append("\n");
        sb.append("    featureType: ").append(toIndentedString(featureType)).append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    mdType: ").append(toIndentedString(mdType)).append("\n");
        sb.append("    title: ").append(toIndentedString(title)).append("\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("    url: ").append(toIndentedString(url)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
