/*
 * GeoNetwork Api Documentation (beta)
 * Learn how to access the catalog using the GeoNetwork REST API.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.fao.geonet.openapi.model;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * FeatureResponse
 */

public class FeatureResponse {
    @JsonProperty("decodeMap")
    private Map<String, List<String>> decodeMap = null;

    public FeatureResponse decodeMap(Map<String, List<String>> decodeMap) {
        this.decodeMap = decodeMap;
        return this;
    }

    public FeatureResponse putDecodeMapItem(String key, List<String> decodeMapItem) {
        if (this.decodeMap == null) {
            this.decodeMap = new HashMap<>();
        }
        this.decodeMap.put(key, decodeMapItem);
        return this;
    }

    /**
     * Get decodeMap
     * 
     * @return decodeMap
     **/
    @ApiModelProperty(value = "")
    public Map<String, List<String>> getDecodeMap() {
        return decodeMap;
    }

    public void setDecodeMap(Map<String, List<String>> decodeMap) {
        this.decodeMap = decodeMap;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        FeatureResponse featureResponse = (FeatureResponse) o;
        return Objects.equals(this.decodeMap, featureResponse.decodeMap);
    }

    @Override
    public int hashCode() {
        return Objects.hash(decodeMap);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class FeatureResponse {\n");

        sb.append("    decodeMap: ").append(toIndentedString(decodeMap)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
