/*
 * GeoNetwork Api Documentation (beta)
 * Learn how to access the catalog using the GeoNetwork REST API.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.fao.geonet.openapi.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;

import io.swagger.annotations.ApiModelProperty;

/**
 * GroupPrivilege
 */

public class GroupPrivilege {
    @JsonProperty("group")
    private Integer group = null;

    @JsonProperty("operations")
    private Map<String, Boolean> operations = null;

    @JsonProperty("reserved")
    private Boolean reserved = null;

    @JsonProperty("userGroup")
    private Boolean userGroup = null;

    /**
     * Gets or Sets userProfiles
     */
    public enum UserProfilesEnum {
        ADMINISTRATOR("Administrator"),

        USERADMIN("UserAdmin"),

        REVIEWER("Reviewer"),

        EDITOR("Editor"),

        REGISTEREDUSER("RegisteredUser"),

        GUEST("Guest"),

        MONITOR("Monitor");

        private String value;

        UserProfilesEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        @JsonCreator
        public static UserProfilesEnum fromValue(String text) {
            for (UserProfilesEnum b : UserProfilesEnum.values()) {
                if (String.valueOf(b.value).equals(text)) {
                    return b;
                }
            }
            return null;
        }
    }

    @JsonProperty("userProfiles")
    private List<UserProfilesEnum> userProfiles = null;

    public GroupPrivilege group(Integer group) {
        this.group = group;
        return this;
    }

    /**
     * Get group
     * 
     * @return group
     **/
    @ApiModelProperty(value = "")
    public Integer getGroup() {
        return group;
    }

    public void setGroup(Integer group) {
        this.group = group;
    }

    public GroupPrivilege operations(Map<String, Boolean> operations) {
        this.operations = operations;
        return this;
    }

    public GroupPrivilege putOperationsItem(String key, Boolean operationsItem) {
        if (this.operations == null) {
            this.operations = new HashMap<>();
        }
        this.operations.put(key, operationsItem);
        return this;
    }

    /**
     * Get operations
     * 
     * @return operations
     **/
    @ApiModelProperty(value = "")
    public Map<String, Boolean> getOperations() {
        return operations;
    }

    public void setOperations(Map<String, Boolean> operations) {
        this.operations = operations;
    }

    public GroupPrivilege reserved(Boolean reserved) {
        this.reserved = reserved;
        return this;
    }

    /**
     * Get reserved
     * 
     * @return reserved
     **/
    @ApiModelProperty(value = "")
    public Boolean isReserved() {
        return reserved;
    }

    public void setReserved(Boolean reserved) {
        this.reserved = reserved;
    }

    public GroupPrivilege userGroup(Boolean userGroup) {
        this.userGroup = userGroup;
        return this;
    }

    /**
     * Get userGroup
     * 
     * @return userGroup
     **/
    @ApiModelProperty(value = "")
    public Boolean isUserGroup() {
        return userGroup;
    }

    public void setUserGroup(Boolean userGroup) {
        this.userGroup = userGroup;
    }

    public GroupPrivilege userProfiles(List<UserProfilesEnum> userProfiles) {
        this.userProfiles = userProfiles;
        return this;
    }

    public GroupPrivilege addUserProfilesItem(UserProfilesEnum userProfilesItem) {
        if (this.userProfiles == null) {
            this.userProfiles = new ArrayList<>();
        }
        this.userProfiles.add(userProfilesItem);
        return this;
    }

    /**
     * Get userProfiles
     * 
     * @return userProfiles
     **/
    @ApiModelProperty(value = "")
    public List<UserProfilesEnum> getUserProfiles() {
        return userProfiles;
    }

    public void setUserProfiles(List<UserProfilesEnum> userProfiles) {
        this.userProfiles = userProfiles;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GroupPrivilege groupPrivilege = (GroupPrivilege) o;
        return Objects.equals(this.group, groupPrivilege.group)
                && Objects.equals(this.operations, groupPrivilege.operations)
                && Objects.equals(this.reserved, groupPrivilege.reserved)
                && Objects.equals(this.userGroup, groupPrivilege.userGroup)
                && Objects.equals(this.userProfiles, groupPrivilege.userProfiles);
    }

    @Override
    public int hashCode() {
        return Objects.hash(group, operations, reserved, userGroup, userProfiles);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class GroupPrivilege {\n");

        sb.append("    group: ").append(toIndentedString(group)).append("\n");
        sb.append("    operations: ").append(toIndentedString(operations)).append("\n");
        sb.append("    reserved: ").append(toIndentedString(reserved)).append("\n");
        sb.append("    userGroup: ").append(toIndentedString(userGroup)).append("\n");
        sb.append("    userProfiles: ").append(toIndentedString(userProfiles)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
