/*
 * GeoNetwork Api Documentation (beta)
 * Learn how to access the catalog using the GeoNetwork REST API.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.fao.geonet.openapi.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * ISODate
 */

public class ISODate {
    @JsonProperty("dateAndTime")
    private String dateAndTime = null;

    @JsonProperty("dateAsString")
    private String dateAsString = null;

    @JsonProperty("dateOnly")
    private Boolean dateOnly = null;

    @JsonProperty("dateYearMonthOnly")
    private Boolean dateYearMonthOnly = null;

    @JsonProperty("dateYearOnly")
    private Boolean dateYearOnly = null;

    @JsonProperty("days")
    private Integer days = null;

    @JsonProperty("hours")
    private Integer hours = null;

    @JsonProperty("minutes")
    private Integer minutes = null;

    @JsonProperty("months")
    private Integer months = null;

    @JsonProperty("seconds")
    private Integer seconds = null;

    @JsonProperty("timeAsString")
    private String timeAsString = null;

    @JsonProperty("timeInSeconds")
    private Long timeInSeconds = null;

    @JsonProperty("years")
    private Integer years = null;

    public ISODate dateAndTime(String dateAndTime) {
        this.dateAndTime = dateAndTime;
        return this;
    }

    /**
     * Get dateAndTime
     * 
     * @return dateAndTime
     **/
    @ApiModelProperty(value = "")
    public String getDateAndTime() {
        return dateAndTime;
    }

    public void setDateAndTime(String dateAndTime) {
        this.dateAndTime = dateAndTime;
    }

    public ISODate dateAsString(String dateAsString) {
        this.dateAsString = dateAsString;
        return this;
    }

    /**
     * Get dateAsString
     * 
     * @return dateAsString
     **/
    @ApiModelProperty(value = "")
    public String getDateAsString() {
        return dateAsString;
    }

    public void setDateAsString(String dateAsString) {
        this.dateAsString = dateAsString;
    }

    public ISODate dateOnly(Boolean dateOnly) {
        this.dateOnly = dateOnly;
        return this;
    }

    /**
     * Get dateOnly
     * 
     * @return dateOnly
     **/
    @ApiModelProperty(value = "")
    public Boolean isDateOnly() {
        return dateOnly;
    }

    public void setDateOnly(Boolean dateOnly) {
        this.dateOnly = dateOnly;
    }

    public ISODate dateYearMonthOnly(Boolean dateYearMonthOnly) {
        this.dateYearMonthOnly = dateYearMonthOnly;
        return this;
    }

    /**
     * Get dateYearMonthOnly
     * 
     * @return dateYearMonthOnly
     **/
    @ApiModelProperty(value = "")
    public Boolean isDateYearMonthOnly() {
        return dateYearMonthOnly;
    }

    public void setDateYearMonthOnly(Boolean dateYearMonthOnly) {
        this.dateYearMonthOnly = dateYearMonthOnly;
    }

    public ISODate dateYearOnly(Boolean dateYearOnly) {
        this.dateYearOnly = dateYearOnly;
        return this;
    }

    /**
     * Get dateYearOnly
     * 
     * @return dateYearOnly
     **/
    @ApiModelProperty(value = "")
    public Boolean isDateYearOnly() {
        return dateYearOnly;
    }

    public void setDateYearOnly(Boolean dateYearOnly) {
        this.dateYearOnly = dateYearOnly;
    }

    public ISODate days(Integer days) {
        this.days = days;
        return this;
    }

    /**
     * Get days
     * 
     * @return days
     **/
    @ApiModelProperty(value = "")
    public Integer getDays() {
        return days;
    }

    public void setDays(Integer days) {
        this.days = days;
    }

    public ISODate hours(Integer hours) {
        this.hours = hours;
        return this;
    }

    /**
     * Get hours
     * 
     * @return hours
     **/
    @ApiModelProperty(value = "")
    public Integer getHours() {
        return hours;
    }

    public void setHours(Integer hours) {
        this.hours = hours;
    }

    public ISODate minutes(Integer minutes) {
        this.minutes = minutes;
        return this;
    }

    /**
     * Get minutes
     * 
     * @return minutes
     **/
    @ApiModelProperty(value = "")
    public Integer getMinutes() {
        return minutes;
    }

    public void setMinutes(Integer minutes) {
        this.minutes = minutes;
    }

    public ISODate months(Integer months) {
        this.months = months;
        return this;
    }

    /**
     * Get months
     * 
     * @return months
     **/
    @ApiModelProperty(value = "")
    public Integer getMonths() {
        return months;
    }

    public void setMonths(Integer months) {
        this.months = months;
    }

    public ISODate seconds(Integer seconds) {
        this.seconds = seconds;
        return this;
    }

    /**
     * Get seconds
     * 
     * @return seconds
     **/
    @ApiModelProperty(value = "")
    public Integer getSeconds() {
        return seconds;
    }

    public void setSeconds(Integer seconds) {
        this.seconds = seconds;
    }

    public ISODate timeAsString(String timeAsString) {
        this.timeAsString = timeAsString;
        return this;
    }

    /**
     * Get timeAsString
     * 
     * @return timeAsString
     **/
    @ApiModelProperty(value = "")
    public String getTimeAsString() {
        return timeAsString;
    }

    public void setTimeAsString(String timeAsString) {
        this.timeAsString = timeAsString;
    }

    public ISODate timeInSeconds(Long timeInSeconds) {
        this.timeInSeconds = timeInSeconds;
        return this;
    }

    /**
     * Get timeInSeconds
     * 
     * @return timeInSeconds
     **/
    @ApiModelProperty(value = "")
    public Long getTimeInSeconds() {
        return timeInSeconds;
    }

    public void setTimeInSeconds(Long timeInSeconds) {
        this.timeInSeconds = timeInSeconds;
    }

    public ISODate years(Integer years) {
        this.years = years;
        return this;
    }

    /**
     * Get years
     * 
     * @return years
     **/
    @ApiModelProperty(value = "")
    public Integer getYears() {
        return years;
    }

    public void setYears(Integer years) {
        this.years = years;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ISODate isODate = (ISODate) o;
        return Objects.equals(this.dateAndTime, isODate.dateAndTime)
                && Objects.equals(this.dateAsString, isODate.dateAsString)
                && Objects.equals(this.dateOnly, isODate.dateOnly)
                && Objects.equals(this.dateYearMonthOnly, isODate.dateYearMonthOnly)
                && Objects.equals(this.dateYearOnly, isODate.dateYearOnly) && Objects.equals(this.days, isODate.days)
                && Objects.equals(this.hours, isODate.hours) && Objects.equals(this.minutes, isODate.minutes)
                && Objects.equals(this.months, isODate.months) && Objects.equals(this.seconds, isODate.seconds)
                && Objects.equals(this.timeAsString, isODate.timeAsString)
                && Objects.equals(this.timeInSeconds, isODate.timeInSeconds)
                && Objects.equals(this.years, isODate.years);
    }

    @Override
    public int hashCode() {
        return Objects.hash(dateAndTime, dateAsString, dateOnly, dateYearMonthOnly, dateYearOnly, days, hours, minutes,
                months, seconds, timeAsString, timeInSeconds, years);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ISODate {\n");

        sb.append("    dateAndTime: ").append(toIndentedString(dateAndTime)).append("\n");
        sb.append("    dateAsString: ").append(toIndentedString(dateAsString)).append("\n");
        sb.append("    dateOnly: ").append(toIndentedString(dateOnly)).append("\n");
        sb.append("    dateYearMonthOnly: ").append(toIndentedString(dateYearMonthOnly)).append("\n");
        sb.append("    dateYearOnly: ").append(toIndentedString(dateYearOnly)).append("\n");
        sb.append("    days: ").append(toIndentedString(days)).append("\n");
        sb.append("    hours: ").append(toIndentedString(hours)).append("\n");
        sb.append("    minutes: ").append(toIndentedString(minutes)).append("\n");
        sb.append("    months: ").append(toIndentedString(months)).append("\n");
        sb.append("    seconds: ").append(toIndentedString(seconds)).append("\n");
        sb.append("    timeAsString: ").append(toIndentedString(timeAsString)).append("\n");
        sb.append("    timeInSeconds: ").append(toIndentedString(timeInSeconds)).append("\n");
        sb.append("    years: ").append(toIndentedString(years)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
