/*
 * GeoNetwork Api Documentation (beta)
 * Learn how to access the catalog using the GeoNetwork REST API.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.fao.geonet.openapi.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;

import io.swagger.annotations.ApiModelProperty;

/**
 * Link
 */

public class Link {
    @JsonProperty("id")
    private Integer id = null;

    @JsonProperty("lastState")
    private Integer lastState = null;

    @JsonProperty("linkStatus")
    private List<LinkStatus> linkStatus = null;

    /**
     * Gets or Sets linkType
     */
    public enum LinkTypeEnum {
        HTTP("HTTP"),

        METADATA("METADATA");

        private String value;

        LinkTypeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        @JsonCreator
        public static LinkTypeEnum fromValue(String text) {
            for (LinkTypeEnum b : LinkTypeEnum.values()) {
                if (String.valueOf(b.value).equals(text)) {
                    return b;
                }
            }
            return null;
        }
    }

    @JsonProperty("linkType")
    private LinkTypeEnum linkType = null;

    @JsonProperty("protocol")
    private String protocol = null;

    @JsonProperty("records")
    private List<MetadataLink> records = null;

    @JsonProperty("url")
    private String url = null;

    public Link id(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     * 
     * @return id
     **/
    @ApiModelProperty(value = "")
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Link lastState(Integer lastState) {
        this.lastState = lastState;
        return this;
    }

    /**
     * Get lastState
     * 
     * @return lastState
     **/
    @ApiModelProperty(value = "")
    public Integer getLastState() {
        return lastState;
    }

    public void setLastState(Integer lastState) {
        this.lastState = lastState;
    }

    public Link linkStatus(List<LinkStatus> linkStatus) {
        this.linkStatus = linkStatus;
        return this;
    }

    public Link addLinkStatusItem(LinkStatus linkStatusItem) {
        if (this.linkStatus == null) {
            this.linkStatus = new ArrayList<>();
        }
        this.linkStatus.add(linkStatusItem);
        return this;
    }

    /**
     * Get linkStatus
     * 
     * @return linkStatus
     **/
    @ApiModelProperty(value = "")
    public List<LinkStatus> getLinkStatus() {
        return linkStatus;
    }

    public void setLinkStatus(List<LinkStatus> linkStatus) {
        this.linkStatus = linkStatus;
    }

    public Link linkType(LinkTypeEnum linkType) {
        this.linkType = linkType;
        return this;
    }

    /**
     * Get linkType
     * 
     * @return linkType
     **/
    @ApiModelProperty(value = "")
    public LinkTypeEnum getLinkType() {
        return linkType;
    }

    public void setLinkType(LinkTypeEnum linkType) {
        this.linkType = linkType;
    }

    public Link protocol(String protocol) {
        this.protocol = protocol;
        return this;
    }

    /**
     * Get protocol
     * 
     * @return protocol
     **/
    @ApiModelProperty(value = "")
    public String getProtocol() {
        return protocol;
    }

    public void setProtocol(String protocol) {
        this.protocol = protocol;
    }

    public Link records(List<MetadataLink> records) {
        this.records = records;
        return this;
    }

    public Link addRecordsItem(MetadataLink recordsItem) {
        if (this.records == null) {
            this.records = new ArrayList<>();
        }
        this.records.add(recordsItem);
        return this;
    }

    /**
     * Get records
     * 
     * @return records
     **/
    @ApiModelProperty(value = "")
    public List<MetadataLink> getRecords() {
        return records;
    }

    public void setRecords(List<MetadataLink> records) {
        this.records = records;
    }

    public Link url(String url) {
        this.url = url;
        return this;
    }

    /**
     * Get url
     * 
     * @return url
     **/
    @ApiModelProperty(value = "")
    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Link link = (Link) o;
        return Objects.equals(this.id, link.id) && Objects.equals(this.lastState, link.lastState)
                && Objects.equals(this.linkStatus, link.linkStatus) && Objects.equals(this.linkType, link.linkType)
                && Objects.equals(this.protocol, link.protocol) && Objects.equals(this.records, link.records)
                && Objects.equals(this.url, link.url);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, lastState, linkStatus, linkType, protocol, records, url);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Link {\n");

        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    lastState: ").append(toIndentedString(lastState)).append("\n");
        sb.append("    linkStatus: ").append(toIndentedString(linkStatus)).append("\n");
        sb.append("    linkType: ").append(toIndentedString(linkType)).append("\n");
        sb.append("    protocol: ").append(toIndentedString(protocol)).append("\n");
        sb.append("    records: ").append(toIndentedString(records)).append("\n");
        sb.append("    url: ").append(toIndentedString(url)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
