/*
 * GeoNetwork Api Documentation (beta)
 * Learn how to access the catalog using the GeoNetwork REST API.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.fao.geonet.openapi.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * LinkStatus
 */

public class LinkStatus {
    @JsonProperty("batchKey")
    private String batchKey = null;

    @JsonProperty("checkDate")
    private ISODate checkDate = null;

    @JsonProperty("failing")
    private Boolean failing = null;

    @JsonProperty("id")
    private Integer id = null;

    @JsonProperty("statusInfo")
    private String statusInfo = null;

    @JsonProperty("statusValue")
    private String statusValue = null;

    public LinkStatus batchKey(String batchKey) {
        this.batchKey = batchKey;
        return this;
    }

    /**
     * Get batchKey
     * 
     * @return batchKey
     **/
    @ApiModelProperty(value = "")
    public String getBatchKey() {
        return batchKey;
    }

    public void setBatchKey(String batchKey) {
        this.batchKey = batchKey;
    }

    public LinkStatus checkDate(ISODate checkDate) {
        this.checkDate = checkDate;
        return this;
    }

    /**
     * Get checkDate
     * 
     * @return checkDate
     **/
    @ApiModelProperty(value = "")
    public ISODate getCheckDate() {
        return checkDate;
    }

    public void setCheckDate(ISODate checkDate) {
        this.checkDate = checkDate;
    }

    public LinkStatus failing(Boolean failing) {
        this.failing = failing;
        return this;
    }

    /**
     * Get failing
     * 
     * @return failing
     **/
    @ApiModelProperty(value = "")
    public Boolean isFailing() {
        return failing;
    }

    public void setFailing(Boolean failing) {
        this.failing = failing;
    }

    public LinkStatus id(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     * 
     * @return id
     **/
    @ApiModelProperty(value = "")
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public LinkStatus statusInfo(String statusInfo) {
        this.statusInfo = statusInfo;
        return this;
    }

    /**
     * Get statusInfo
     * 
     * @return statusInfo
     **/
    @ApiModelProperty(value = "")
    public String getStatusInfo() {
        return statusInfo;
    }

    public void setStatusInfo(String statusInfo) {
        this.statusInfo = statusInfo;
    }

    public LinkStatus statusValue(String statusValue) {
        this.statusValue = statusValue;
        return this;
    }

    /**
     * Get statusValue
     * 
     * @return statusValue
     **/
    @ApiModelProperty(value = "")
    public String getStatusValue() {
        return statusValue;
    }

    public void setStatusValue(String statusValue) {
        this.statusValue = statusValue;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        LinkStatus linkStatus = (LinkStatus) o;
        return Objects.equals(this.batchKey, linkStatus.batchKey)
                && Objects.equals(this.checkDate, linkStatus.checkDate)
                && Objects.equals(this.failing, linkStatus.failing) && Objects.equals(this.id, linkStatus.id)
                && Objects.equals(this.statusInfo, linkStatus.statusInfo)
                && Objects.equals(this.statusValue, linkStatus.statusValue);
    }

    @Override
    public int hashCode() {
        return Objects.hash(batchKey, checkDate, failing, id, statusInfo, statusValue);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class LinkStatus {\n");

        sb.append("    batchKey: ").append(toIndentedString(batchKey)).append("\n");
        sb.append("    checkDate: ").append(toIndentedString(checkDate)).append("\n");
        sb.append("    failing: ").append(toIndentedString(failing)).append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    statusInfo: ").append(toIndentedString(statusInfo)).append("\n");
        sb.append("    statusValue: ").append(toIndentedString(statusValue)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
