/*
 * GeoNetwork Api Documentation (beta)
 * Learn how to access the catalog using the GeoNetwork REST API.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.fao.geonet.openapi.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * MetadataReplacementProcessingReport
 */

public class MetadataReplacementProcessingReport {
    @JsonProperty("ellapsedTimeInSeconds")
    private Long ellapsedTimeInSeconds = null;

    @JsonProperty("endIsoDateTime")
    private String endIsoDateTime = null;

    @JsonProperty("errors")
    private List<Report> errors = null;

    @JsonProperty("infos")
    private List<InfoReport> infos = null;

    @JsonProperty("metadata")
    private List<Integer> metadata = null;

    @JsonProperty("metadataChanges")
    private Map<String, ReplaceReport> metadataChanges = null;

    @JsonProperty("metadataErrors")
    private Map<String, List<Report>> metadataErrors = null;

    @JsonProperty("metadataInfos")
    private Map<String, List<InfoReport>> metadataInfos = null;

    @JsonProperty("noProcessFoundCount")
    private Integer noProcessFoundCount = null;

    @JsonProperty("numberOfNullRecords")
    private Integer numberOfNullRecords = null;

    @JsonProperty("numberOfRecordNotFound")
    private Integer numberOfRecordNotFound = null;

    @JsonProperty("numberOfRecords")
    private Integer numberOfRecords = null;

    @JsonProperty("numberOfRecordsChanged")
    private Integer numberOfRecordsChanged = null;

    @JsonProperty("numberOfRecordsNotChanged")
    private Integer numberOfRecordsNotChanged = null;

    @JsonProperty("numberOfRecordsNotEditable")
    private Integer numberOfRecordsNotEditable = null;

    @JsonProperty("numberOfRecordsProcessed")
    private Integer numberOfRecordsProcessed = null;

    @JsonProperty("numberOfRecordsWithErrors")
    private Integer numberOfRecordsWithErrors = null;

    @JsonProperty("processId")
    private String processId = null;

    @JsonProperty("running")
    private Boolean running = null;

    @JsonProperty("startIsoDateTime")
    private String startIsoDateTime = null;

    @JsonProperty("totalTimeInSeconds")
    private Long totalTimeInSeconds = null;

    @JsonProperty("type")
    private String type = null;

    @JsonProperty("uuid")
    private String uuid = null;

    public MetadataReplacementProcessingReport ellapsedTimeInSeconds(Long ellapsedTimeInSeconds) {
        this.ellapsedTimeInSeconds = ellapsedTimeInSeconds;
        return this;
    }

    /**
     * Get ellapsedTimeInSeconds
     * 
     * @return ellapsedTimeInSeconds
     **/
    @ApiModelProperty(value = "")
    public Long getEllapsedTimeInSeconds() {
        return ellapsedTimeInSeconds;
    }

    public void setEllapsedTimeInSeconds(Long ellapsedTimeInSeconds) {
        this.ellapsedTimeInSeconds = ellapsedTimeInSeconds;
    }

    public MetadataReplacementProcessingReport endIsoDateTime(String endIsoDateTime) {
        this.endIsoDateTime = endIsoDateTime;
        return this;
    }

    /**
     * Get endIsoDateTime
     * 
     * @return endIsoDateTime
     **/
    @ApiModelProperty(value = "")
    public String getEndIsoDateTime() {
        return endIsoDateTime;
    }

    public void setEndIsoDateTime(String endIsoDateTime) {
        this.endIsoDateTime = endIsoDateTime;
    }

    public MetadataReplacementProcessingReport errors(List<Report> errors) {
        this.errors = errors;
        return this;
    }

    public MetadataReplacementProcessingReport addErrorsItem(Report errorsItem) {
        if (this.errors == null) {
            this.errors = new ArrayList<>();
        }
        this.errors.add(errorsItem);
        return this;
    }

    /**
     * Get errors
     * 
     * @return errors
     **/
    @ApiModelProperty(value = "")
    public List<Report> getErrors() {
        return errors;
    }

    public void setErrors(List<Report> errors) {
        this.errors = errors;
    }

    public MetadataReplacementProcessingReport infos(List<InfoReport> infos) {
        this.infos = infos;
        return this;
    }

    public MetadataReplacementProcessingReport addInfosItem(InfoReport infosItem) {
        if (this.infos == null) {
            this.infos = new ArrayList<>();
        }
        this.infos.add(infosItem);
        return this;
    }

    /**
     * Get infos
     * 
     * @return infos
     **/
    @ApiModelProperty(value = "")
    public List<InfoReport> getInfos() {
        return infos;
    }

    public void setInfos(List<InfoReport> infos) {
        this.infos = infos;
    }

    public MetadataReplacementProcessingReport metadata(List<Integer> metadata) {
        this.metadata = metadata;
        return this;
    }

    public MetadataReplacementProcessingReport addMetadataItem(Integer metadataItem) {
        if (this.metadata == null) {
            this.metadata = new ArrayList<>();
        }
        this.metadata.add(metadataItem);
        return this;
    }

    /**
     * Get metadata
     * 
     * @return metadata
     **/
    @ApiModelProperty(value = "")
    public List<Integer> getMetadata() {
        return metadata;
    }

    public void setMetadata(List<Integer> metadata) {
        this.metadata = metadata;
    }

    public MetadataReplacementProcessingReport metadataChanges(Map<String, ReplaceReport> metadataChanges) {
        this.metadataChanges = metadataChanges;
        return this;
    }

    public MetadataReplacementProcessingReport putMetadataChangesItem(String key, ReplaceReport metadataChangesItem) {
        if (this.metadataChanges == null) {
            this.metadataChanges = new HashMap<>();
        }
        this.metadataChanges.put(key, metadataChangesItem);
        return this;
    }

    /**
     * Get metadataChanges
     * 
     * @return metadataChanges
     **/
    @ApiModelProperty(value = "")
    public Map<String, ReplaceReport> getMetadataChanges() {
        return metadataChanges;
    }

    public void setMetadataChanges(Map<String, ReplaceReport> metadataChanges) {
        this.metadataChanges = metadataChanges;
    }

    public MetadataReplacementProcessingReport metadataErrors(Map<String, List<Report>> metadataErrors) {
        this.metadataErrors = metadataErrors;
        return this;
    }

    public MetadataReplacementProcessingReport putMetadataErrorsItem(String key, List<Report> metadataErrorsItem) {
        if (this.metadataErrors == null) {
            this.metadataErrors = new HashMap<>();
        }
        this.metadataErrors.put(key, metadataErrorsItem);
        return this;
    }

    /**
     * Get metadataErrors
     * 
     * @return metadataErrors
     **/
    @ApiModelProperty(value = "")
    public Map<String, List<Report>> getMetadataErrors() {
        return metadataErrors;
    }

    public void setMetadataErrors(Map<String, List<Report>> metadataErrors) {
        this.metadataErrors = metadataErrors;
    }

    public MetadataReplacementProcessingReport metadataInfos(Map<String, List<InfoReport>> metadataInfos) {
        this.metadataInfos = metadataInfos;
        return this;
    }

    public MetadataReplacementProcessingReport putMetadataInfosItem(String key, List<InfoReport> metadataInfosItem) {
        if (this.metadataInfos == null) {
            this.metadataInfos = new HashMap<>();
        }
        this.metadataInfos.put(key, metadataInfosItem);
        return this;
    }

    /**
     * Get metadataInfos
     * 
     * @return metadataInfos
     **/
    @ApiModelProperty(value = "")
    public Map<String, List<InfoReport>> getMetadataInfos() {
        return metadataInfos;
    }

    public void setMetadataInfos(Map<String, List<InfoReport>> metadataInfos) {
        this.metadataInfos = metadataInfos;
    }

    public MetadataReplacementProcessingReport noProcessFoundCount(Integer noProcessFoundCount) {
        this.noProcessFoundCount = noProcessFoundCount;
        return this;
    }

    /**
     * Get noProcessFoundCount
     * 
     * @return noProcessFoundCount
     **/
    @ApiModelProperty(value = "")
    public Integer getNoProcessFoundCount() {
        return noProcessFoundCount;
    }

    public void setNoProcessFoundCount(Integer noProcessFoundCount) {
        this.noProcessFoundCount = noProcessFoundCount;
    }

    public MetadataReplacementProcessingReport numberOfNullRecords(Integer numberOfNullRecords) {
        this.numberOfNullRecords = numberOfNullRecords;
        return this;
    }

    /**
     * Get numberOfNullRecords
     * 
     * @return numberOfNullRecords
     **/
    @ApiModelProperty(value = "")
    public Integer getNumberOfNullRecords() {
        return numberOfNullRecords;
    }

    public void setNumberOfNullRecords(Integer numberOfNullRecords) {
        this.numberOfNullRecords = numberOfNullRecords;
    }

    public MetadataReplacementProcessingReport numberOfRecordNotFound(Integer numberOfRecordNotFound) {
        this.numberOfRecordNotFound = numberOfRecordNotFound;
        return this;
    }

    /**
     * Get numberOfRecordNotFound
     * 
     * @return numberOfRecordNotFound
     **/
    @ApiModelProperty(value = "")
    public Integer getNumberOfRecordNotFound() {
        return numberOfRecordNotFound;
    }

    public void setNumberOfRecordNotFound(Integer numberOfRecordNotFound) {
        this.numberOfRecordNotFound = numberOfRecordNotFound;
    }

    public MetadataReplacementProcessingReport numberOfRecords(Integer numberOfRecords) {
        this.numberOfRecords = numberOfRecords;
        return this;
    }

    /**
     * Get numberOfRecords
     * 
     * @return numberOfRecords
     **/
    @ApiModelProperty(value = "")
    public Integer getNumberOfRecords() {
        return numberOfRecords;
    }

    public void setNumberOfRecords(Integer numberOfRecords) {
        this.numberOfRecords = numberOfRecords;
    }

    public MetadataReplacementProcessingReport numberOfRecordsChanged(Integer numberOfRecordsChanged) {
        this.numberOfRecordsChanged = numberOfRecordsChanged;
        return this;
    }

    /**
     * Get numberOfRecordsChanged
     * 
     * @return numberOfRecordsChanged
     **/
    @ApiModelProperty(value = "")
    public Integer getNumberOfRecordsChanged() {
        return numberOfRecordsChanged;
    }

    public void setNumberOfRecordsChanged(Integer numberOfRecordsChanged) {
        this.numberOfRecordsChanged = numberOfRecordsChanged;
    }

    public MetadataReplacementProcessingReport numberOfRecordsNotChanged(Integer numberOfRecordsNotChanged) {
        this.numberOfRecordsNotChanged = numberOfRecordsNotChanged;
        return this;
    }

    /**
     * Get numberOfRecordsNotChanged
     * 
     * @return numberOfRecordsNotChanged
     **/
    @ApiModelProperty(value = "")
    public Integer getNumberOfRecordsNotChanged() {
        return numberOfRecordsNotChanged;
    }

    public void setNumberOfRecordsNotChanged(Integer numberOfRecordsNotChanged) {
        this.numberOfRecordsNotChanged = numberOfRecordsNotChanged;
    }

    public MetadataReplacementProcessingReport numberOfRecordsNotEditable(Integer numberOfRecordsNotEditable) {
        this.numberOfRecordsNotEditable = numberOfRecordsNotEditable;
        return this;
    }

    /**
     * Get numberOfRecordsNotEditable
     * 
     * @return numberOfRecordsNotEditable
     **/
    @ApiModelProperty(value = "")
    public Integer getNumberOfRecordsNotEditable() {
        return numberOfRecordsNotEditable;
    }

    public void setNumberOfRecordsNotEditable(Integer numberOfRecordsNotEditable) {
        this.numberOfRecordsNotEditable = numberOfRecordsNotEditable;
    }

    public MetadataReplacementProcessingReport numberOfRecordsProcessed(Integer numberOfRecordsProcessed) {
        this.numberOfRecordsProcessed = numberOfRecordsProcessed;
        return this;
    }

    /**
     * Get numberOfRecordsProcessed
     * 
     * @return numberOfRecordsProcessed
     **/
    @ApiModelProperty(value = "")
    public Integer getNumberOfRecordsProcessed() {
        return numberOfRecordsProcessed;
    }

    public void setNumberOfRecordsProcessed(Integer numberOfRecordsProcessed) {
        this.numberOfRecordsProcessed = numberOfRecordsProcessed;
    }

    public MetadataReplacementProcessingReport numberOfRecordsWithErrors(Integer numberOfRecordsWithErrors) {
        this.numberOfRecordsWithErrors = numberOfRecordsWithErrors;
        return this;
    }

    /**
     * Get numberOfRecordsWithErrors
     * 
     * @return numberOfRecordsWithErrors
     **/
    @ApiModelProperty(value = "")
    public Integer getNumberOfRecordsWithErrors() {
        return numberOfRecordsWithErrors;
    }

    public void setNumberOfRecordsWithErrors(Integer numberOfRecordsWithErrors) {
        this.numberOfRecordsWithErrors = numberOfRecordsWithErrors;
    }

    public MetadataReplacementProcessingReport processId(String processId) {
        this.processId = processId;
        return this;
    }

    /**
     * Get processId
     * 
     * @return processId
     **/
    @ApiModelProperty(value = "")
    public String getProcessId() {
        return processId;
    }

    public void setProcessId(String processId) {
        this.processId = processId;
    }

    public MetadataReplacementProcessingReport running(Boolean running) {
        this.running = running;
        return this;
    }

    /**
     * Get running
     * 
     * @return running
     **/
    @ApiModelProperty(value = "")
    public Boolean isRunning() {
        return running;
    }

    public void setRunning(Boolean running) {
        this.running = running;
    }

    public MetadataReplacementProcessingReport startIsoDateTime(String startIsoDateTime) {
        this.startIsoDateTime = startIsoDateTime;
        return this;
    }

    /**
     * Get startIsoDateTime
     * 
     * @return startIsoDateTime
     **/
    @ApiModelProperty(value = "")
    public String getStartIsoDateTime() {
        return startIsoDateTime;
    }

    public void setStartIsoDateTime(String startIsoDateTime) {
        this.startIsoDateTime = startIsoDateTime;
    }

    public MetadataReplacementProcessingReport totalTimeInSeconds(Long totalTimeInSeconds) {
        this.totalTimeInSeconds = totalTimeInSeconds;
        return this;
    }

    /**
     * Get totalTimeInSeconds
     * 
     * @return totalTimeInSeconds
     **/
    @ApiModelProperty(value = "")
    public Long getTotalTimeInSeconds() {
        return totalTimeInSeconds;
    }

    public void setTotalTimeInSeconds(Long totalTimeInSeconds) {
        this.totalTimeInSeconds = totalTimeInSeconds;
    }

    public MetadataReplacementProcessingReport type(String type) {
        this.type = type;
        return this;
    }

    /**
     * Get type
     * 
     * @return type
     **/
    @ApiModelProperty(value = "")
    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public MetadataReplacementProcessingReport uuid(String uuid) {
        this.uuid = uuid;
        return this;
    }

    /**
     * Get uuid
     * 
     * @return uuid
     **/
    @ApiModelProperty(value = "")
    public String getUuid() {
        return uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        MetadataReplacementProcessingReport metadataReplacementProcessingReport = (MetadataReplacementProcessingReport) o;
        return Objects.equals(this.ellapsedTimeInSeconds, metadataReplacementProcessingReport.ellapsedTimeInSeconds)
                && Objects.equals(this.endIsoDateTime, metadataReplacementProcessingReport.endIsoDateTime)
                && Objects.equals(this.errors, metadataReplacementProcessingReport.errors)
                && Objects.equals(this.infos, metadataReplacementProcessingReport.infos)
                && Objects.equals(this.metadata, metadataReplacementProcessingReport.metadata)
                && Objects.equals(this.metadataChanges, metadataReplacementProcessingReport.metadataChanges)
                && Objects.equals(this.metadataErrors, metadataReplacementProcessingReport.metadataErrors)
                && Objects.equals(this.metadataInfos, metadataReplacementProcessingReport.metadataInfos)
                && Objects.equals(this.noProcessFoundCount, metadataReplacementProcessingReport.noProcessFoundCount)
                && Objects.equals(this.numberOfNullRecords, metadataReplacementProcessingReport.numberOfNullRecords)
                && Objects.equals(this.numberOfRecordNotFound,
                        metadataReplacementProcessingReport.numberOfRecordNotFound)
                && Objects.equals(this.numberOfRecords, metadataReplacementProcessingReport.numberOfRecords)
                && Objects.equals(this.numberOfRecordsChanged,
                        metadataReplacementProcessingReport.numberOfRecordsChanged)
                && Objects.equals(this.numberOfRecordsNotChanged,
                        metadataReplacementProcessingReport.numberOfRecordsNotChanged)
                && Objects.equals(this.numberOfRecordsNotEditable,
                        metadataReplacementProcessingReport.numberOfRecordsNotEditable)
                && Objects.equals(this.numberOfRecordsProcessed,
                        metadataReplacementProcessingReport.numberOfRecordsProcessed)
                && Objects.equals(this.numberOfRecordsWithErrors,
                        metadataReplacementProcessingReport.numberOfRecordsWithErrors)
                && Objects.equals(this.processId, metadataReplacementProcessingReport.processId)
                && Objects.equals(this.running, metadataReplacementProcessingReport.running)
                && Objects.equals(this.startIsoDateTime, metadataReplacementProcessingReport.startIsoDateTime)
                && Objects.equals(this.totalTimeInSeconds, metadataReplacementProcessingReport.totalTimeInSeconds)
                && Objects.equals(this.type, metadataReplacementProcessingReport.type)
                && Objects.equals(this.uuid, metadataReplacementProcessingReport.uuid);
    }

    @Override
    public int hashCode() {
        return Objects.hash(ellapsedTimeInSeconds, endIsoDateTime, errors, infos, metadata, metadataChanges,
                metadataErrors, metadataInfos, noProcessFoundCount, numberOfNullRecords, numberOfRecordNotFound,
                numberOfRecords, numberOfRecordsChanged, numberOfRecordsNotChanged, numberOfRecordsNotEditable,
                numberOfRecordsProcessed, numberOfRecordsWithErrors, processId, running, startIsoDateTime,
                totalTimeInSeconds, type, uuid);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class MetadataReplacementProcessingReport {\n");

        sb.append("    ellapsedTimeInSeconds: ").append(toIndentedString(ellapsedTimeInSeconds)).append("\n");
        sb.append("    endIsoDateTime: ").append(toIndentedString(endIsoDateTime)).append("\n");
        sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
        sb.append("    infos: ").append(toIndentedString(infos)).append("\n");
        sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
        sb.append("    metadataChanges: ").append(toIndentedString(metadataChanges)).append("\n");
        sb.append("    metadataErrors: ").append(toIndentedString(metadataErrors)).append("\n");
        sb.append("    metadataInfos: ").append(toIndentedString(metadataInfos)).append("\n");
        sb.append("    noProcessFoundCount: ").append(toIndentedString(noProcessFoundCount)).append("\n");
        sb.append("    numberOfNullRecords: ").append(toIndentedString(numberOfNullRecords)).append("\n");
        sb.append("    numberOfRecordNotFound: ").append(toIndentedString(numberOfRecordNotFound)).append("\n");
        sb.append("    numberOfRecords: ").append(toIndentedString(numberOfRecords)).append("\n");
        sb.append("    numberOfRecordsChanged: ").append(toIndentedString(numberOfRecordsChanged)).append("\n");
        sb.append("    numberOfRecordsNotChanged: ").append(toIndentedString(numberOfRecordsNotChanged)).append("\n");
        sb.append("    numberOfRecordsNotEditable: ").append(toIndentedString(numberOfRecordsNotEditable)).append("\n");
        sb.append("    numberOfRecordsProcessed: ").append(toIndentedString(numberOfRecordsProcessed)).append("\n");
        sb.append("    numberOfRecordsWithErrors: ").append(toIndentedString(numberOfRecordsWithErrors)).append("\n");
        sb.append("    processId: ").append(toIndentedString(processId)).append("\n");
        sb.append("    running: ").append(toIndentedString(running)).append("\n");
        sb.append("    startIsoDateTime: ").append(toIndentedString(startIsoDateTime)).append("\n");
        sb.append("    totalTimeInSeconds: ").append(toIndentedString(totalTimeInSeconds)).append("\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
