/*
 * GeoNetwork Api Documentation (beta)
 * Learn how to access the catalog using the GeoNetwork REST API.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.fao.geonet.openapi.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * MetadataIdentifierTemplate
 */

public class MetadataIdentifierTemplate {
    @JsonProperty("id")
    private Integer id = null;

    @JsonProperty("name")
    private String name = null;

    @JsonProperty("systemDefault")
    private Boolean systemDefault = null;

    @JsonProperty("systemProvided")
    private Boolean systemProvided = null;

    @JsonProperty("systemProvided_JPAWorkaround")
    private String systemProvidedJPAWorkaround = null;

    @JsonProperty("template")
    private String template = null;

    public MetadataIdentifierTemplate id(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     * 
     * @return id
     **/
    @ApiModelProperty(value = "")
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public MetadataIdentifierTemplate name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get name
     * 
     * @return name
     **/
    @ApiModelProperty(value = "")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public MetadataIdentifierTemplate systemDefault(Boolean systemDefault) {
        this.systemDefault = systemDefault;
        return this;
    }

    /**
     * Get systemDefault
     * 
     * @return systemDefault
     **/
    @ApiModelProperty(value = "")
    public Boolean isSystemDefault() {
        return systemDefault;
    }

    public void setSystemDefault(Boolean systemDefault) {
        this.systemDefault = systemDefault;
    }

    public MetadataIdentifierTemplate systemProvided(Boolean systemProvided) {
        this.systemProvided = systemProvided;
        return this;
    }

    /**
     * Get systemProvided
     * 
     * @return systemProvided
     **/
    @ApiModelProperty(value = "")
    public Boolean isSystemProvided() {
        return systemProvided;
    }

    public void setSystemProvided(Boolean systemProvided) {
        this.systemProvided = systemProvided;
    }

    public MetadataIdentifierTemplate systemProvidedJPAWorkaround(String systemProvidedJPAWorkaround) {
        this.systemProvidedJPAWorkaround = systemProvidedJPAWorkaround;
        return this;
    }

    /**
     * Get systemProvidedJPAWorkaround
     * 
     * @return systemProvidedJPAWorkaround
     **/
    @ApiModelProperty(value = "")
    public String getSystemProvidedJPAWorkaround() {
        return systemProvidedJPAWorkaround;
    }

    public void setSystemProvidedJPAWorkaround(String systemProvidedJPAWorkaround) {
        this.systemProvidedJPAWorkaround = systemProvidedJPAWorkaround;
    }

    public MetadataIdentifierTemplate template(String template) {
        this.template = template;
        return this;
    }

    /**
     * Get template
     * 
     * @return template
     **/
    @ApiModelProperty(value = "")
    public String getTemplate() {
        return template;
    }

    public void setTemplate(String template) {
        this.template = template;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        MetadataIdentifierTemplate metadataIdentifierTemplate = (MetadataIdentifierTemplate) o;
        return Objects.equals(this.id, metadataIdentifierTemplate.id)
                && Objects.equals(this.name, metadataIdentifierTemplate.name)
                && Objects.equals(this.systemDefault, metadataIdentifierTemplate.systemDefault)
                && Objects.equals(this.systemProvided, metadataIdentifierTemplate.systemProvided)
                && Objects.equals(this.systemProvidedJPAWorkaround,
                        metadataIdentifierTemplate.systemProvidedJPAWorkaround)
                && Objects.equals(this.template, metadataIdentifierTemplate.template);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, name, systemDefault, systemProvided, systemProvidedJPAWorkaround, template);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class MetadataIdentifierTemplate {\n");

        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    systemDefault: ").append(toIndentedString(systemDefault)).append("\n");
        sb.append("    systemProvided: ").append(toIndentedString(systemProvided)).append("\n");
        sb.append("    systemProvidedJPAWorkaround: ").append(toIndentedString(systemProvidedJPAWorkaround))
                .append("\n");
        sb.append("    template: ").append(toIndentedString(template)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
