/*
 * GeoNetwork Api Documentation (beta)
 * Learn how to access the catalog using the GeoNetwork REST API.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.fao.geonet.openapi.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * MetadataWorkflowStatusResponse
 */

public class MetadataWorkflowStatusResponse {
    @JsonProperty("currentStatus")
    private MetadataStatus currentStatus = null;

    @JsonProperty("hasEditPermission")
    private Boolean hasEditPermission = null;

    @JsonProperty("reviewers")
    private List<User> reviewers = null;

    @JsonProperty("status")
    private List<StatusValue> status = null;

    public MetadataWorkflowStatusResponse currentStatus(MetadataStatus currentStatus) {
        this.currentStatus = currentStatus;
        return this;
    }

    /**
     * Get currentStatus
     * 
     * @return currentStatus
     **/
    @ApiModelProperty(value = "")
    public MetadataStatus getCurrentStatus() {
        return currentStatus;
    }

    public void setCurrentStatus(MetadataStatus currentStatus) {
        this.currentStatus = currentStatus;
    }

    public MetadataWorkflowStatusResponse hasEditPermission(Boolean hasEditPermission) {
        this.hasEditPermission = hasEditPermission;
        return this;
    }

    /**
     * Get hasEditPermission
     * 
     * @return hasEditPermission
     **/
    @ApiModelProperty(value = "")
    public Boolean isHasEditPermission() {
        return hasEditPermission;
    }

    public void setHasEditPermission(Boolean hasEditPermission) {
        this.hasEditPermission = hasEditPermission;
    }

    public MetadataWorkflowStatusResponse reviewers(List<User> reviewers) {
        this.reviewers = reviewers;
        return this;
    }

    public MetadataWorkflowStatusResponse addReviewersItem(User reviewersItem) {
        if (this.reviewers == null) {
            this.reviewers = new ArrayList<>();
        }
        this.reviewers.add(reviewersItem);
        return this;
    }

    /**
     * Get reviewers
     * 
     * @return reviewers
     **/
    @ApiModelProperty(value = "")
    public List<User> getReviewers() {
        return reviewers;
    }

    public void setReviewers(List<User> reviewers) {
        this.reviewers = reviewers;
    }

    public MetadataWorkflowStatusResponse status(List<StatusValue> status) {
        this.status = status;
        return this;
    }

    public MetadataWorkflowStatusResponse addStatusItem(StatusValue statusItem) {
        if (this.status == null) {
            this.status = new ArrayList<>();
        }
        this.status.add(statusItem);
        return this;
    }

    /**
     * Get status
     * 
     * @return status
     **/
    @ApiModelProperty(value = "")
    public List<StatusValue> getStatus() {
        return status;
    }

    public void setStatus(List<StatusValue> status) {
        this.status = status;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        MetadataWorkflowStatusResponse metadataWorkflowStatusResponse = (MetadataWorkflowStatusResponse) o;
        return Objects.equals(this.currentStatus, metadataWorkflowStatusResponse.currentStatus)
                && Objects.equals(this.hasEditPermission, metadataWorkflowStatusResponse.hasEditPermission)
                && Objects.equals(this.reviewers, metadataWorkflowStatusResponse.reviewers)
                && Objects.equals(this.status, metadataWorkflowStatusResponse.status);
    }

    @Override
    public int hashCode() {
        return Objects.hash(currentStatus, hasEditPermission, reviewers, status);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class MetadataWorkflowStatusResponse {\n");

        sb.append("    currentStatus: ").append(toIndentedString(currentStatus)).append("\n");
        sb.append("    hasEditPermission: ").append(toIndentedString(hasEditPermission)).append("\n");
        sb.append("    reviewers: ").append(toIndentedString(reviewers)).append("\n");
        sb.append("    status: ").append(toIndentedString(status)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
