/*
 * GeoNetwork Api Documentation (beta)
 * Learn how to access the catalog using the GeoNetwork REST API.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.fao.geonet.openapi.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * MetadataLink
 */

public class MetadataLink {
    @JsonProperty("metadataId")
    private Integer metadataId = null;

    @JsonProperty("metadataUuid")
    private String metadataUuid = null;

    public MetadataLink metadataId(Integer metadataId) {
        this.metadataId = metadataId;
        return this;
    }

    /**
     * Get metadataId
     * 
     * @return metadataId
     **/
    @ApiModelProperty(value = "")
    public Integer getMetadataId() {
        return metadataId;
    }

    public void setMetadataId(Integer metadataId) {
        this.metadataId = metadataId;
    }

    public MetadataLink metadataUuid(String metadataUuid) {
        this.metadataUuid = metadataUuid;
        return this;
    }

    /**
     * Get metadataUuid
     * 
     * @return metadataUuid
     **/
    @ApiModelProperty(value = "")
    public String getMetadataUuid() {
        return metadataUuid;
    }

    public void setMetadataUuid(String metadataUuid) {
        this.metadataUuid = metadataUuid;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        MetadataLink metadataLink = (MetadataLink) o;
        return Objects.equals(this.metadataId, metadataLink.metadataId)
                && Objects.equals(this.metadataUuid, metadataLink.metadataUuid);
    }

    @Override
    public int hashCode() {
        return Objects.hash(metadataId, metadataUuid);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class MetadataLink {\n");

        sb.append("    metadataId: ").append(toIndentedString(metadataId)).append("\n");
        sb.append("    metadataUuid: ").append(toIndentedString(metadataUuid)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
