/*
 * GeoNetwork Api Documentation (beta)
 * Learn how to access the catalog using the GeoNetwork REST API.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.fao.geonet.openapi.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * ProcessingReport
 */

public class ProcessingReport {
    @JsonProperty("ellapsedTimeInSeconds")
    private Long ellapsedTimeInSeconds = null;

    @JsonProperty("endIsoDateTime")
    private String endIsoDateTime = null;

    @JsonProperty("errors")
    private List<Report> errors = null;

    @JsonProperty("infos")
    private List<InfoReport> infos = null;

    @JsonProperty("running")
    private Boolean running = null;

    @JsonProperty("startIsoDateTime")
    private String startIsoDateTime = null;

    @JsonProperty("totalTimeInSeconds")
    private Long totalTimeInSeconds = null;

    @JsonProperty("type")
    private String type = null;

    @JsonProperty("uuid")
    private String uuid = null;

    public ProcessingReport ellapsedTimeInSeconds(Long ellapsedTimeInSeconds) {
        this.ellapsedTimeInSeconds = ellapsedTimeInSeconds;
        return this;
    }

    /**
     * Get ellapsedTimeInSeconds
     * 
     * @return ellapsedTimeInSeconds
     **/
    @ApiModelProperty(value = "")
    public Long getEllapsedTimeInSeconds() {
        return ellapsedTimeInSeconds;
    }

    public void setEllapsedTimeInSeconds(Long ellapsedTimeInSeconds) {
        this.ellapsedTimeInSeconds = ellapsedTimeInSeconds;
    }

    public ProcessingReport endIsoDateTime(String endIsoDateTime) {
        this.endIsoDateTime = endIsoDateTime;
        return this;
    }

    /**
     * Get endIsoDateTime
     * 
     * @return endIsoDateTime
     **/
    @ApiModelProperty(value = "")
    public String getEndIsoDateTime() {
        return endIsoDateTime;
    }

    public void setEndIsoDateTime(String endIsoDateTime) {
        this.endIsoDateTime = endIsoDateTime;
    }

    public ProcessingReport errors(List<Report> errors) {
        this.errors = errors;
        return this;
    }

    public ProcessingReport addErrorsItem(Report errorsItem) {
        if (this.errors == null) {
            this.errors = new ArrayList<>();
        }
        this.errors.add(errorsItem);
        return this;
    }

    /**
     * Get errors
     * 
     * @return errors
     **/
    @ApiModelProperty(value = "")
    public List<Report> getErrors() {
        return errors;
    }

    public void setErrors(List<Report> errors) {
        this.errors = errors;
    }

    public ProcessingReport infos(List<InfoReport> infos) {
        this.infos = infos;
        return this;
    }

    public ProcessingReport addInfosItem(InfoReport infosItem) {
        if (this.infos == null) {
            this.infos = new ArrayList<>();
        }
        this.infos.add(infosItem);
        return this;
    }

    /**
     * Get infos
     * 
     * @return infos
     **/
    @ApiModelProperty(value = "")
    public List<InfoReport> getInfos() {
        return infos;
    }

    public void setInfos(List<InfoReport> infos) {
        this.infos = infos;
    }

    public ProcessingReport running(Boolean running) {
        this.running = running;
        return this;
    }

    /**
     * Get running
     * 
     * @return running
     **/
    @ApiModelProperty(value = "")
    public Boolean isRunning() {
        return running;
    }

    public void setRunning(Boolean running) {
        this.running = running;
    }

    public ProcessingReport startIsoDateTime(String startIsoDateTime) {
        this.startIsoDateTime = startIsoDateTime;
        return this;
    }

    /**
     * Get startIsoDateTime
     * 
     * @return startIsoDateTime
     **/
    @ApiModelProperty(value = "")
    public String getStartIsoDateTime() {
        return startIsoDateTime;
    }

    public void setStartIsoDateTime(String startIsoDateTime) {
        this.startIsoDateTime = startIsoDateTime;
    }

    public ProcessingReport totalTimeInSeconds(Long totalTimeInSeconds) {
        this.totalTimeInSeconds = totalTimeInSeconds;
        return this;
    }

    /**
     * Get totalTimeInSeconds
     * 
     * @return totalTimeInSeconds
     **/
    @ApiModelProperty(value = "")
    public Long getTotalTimeInSeconds() {
        return totalTimeInSeconds;
    }

    public void setTotalTimeInSeconds(Long totalTimeInSeconds) {
        this.totalTimeInSeconds = totalTimeInSeconds;
    }

    public ProcessingReport type(String type) {
        this.type = type;
        return this;
    }

    /**
     * Get type
     * 
     * @return type
     **/
    @ApiModelProperty(value = "")
    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public ProcessingReport uuid(String uuid) {
        this.uuid = uuid;
        return this;
    }

    /**
     * Get uuid
     * 
     * @return uuid
     **/
    @ApiModelProperty(value = "")
    public String getUuid() {
        return uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ProcessingReport processingReport = (ProcessingReport) o;
        return Objects.equals(this.ellapsedTimeInSeconds, processingReport.ellapsedTimeInSeconds)
                && Objects.equals(this.endIsoDateTime, processingReport.endIsoDateTime)
                && Objects.equals(this.errors, processingReport.errors)
                && Objects.equals(this.infos, processingReport.infos)
                && Objects.equals(this.running, processingReport.running)
                && Objects.equals(this.startIsoDateTime, processingReport.startIsoDateTime)
                && Objects.equals(this.totalTimeInSeconds, processingReport.totalTimeInSeconds)
                && Objects.equals(this.type, processingReport.type) && Objects.equals(this.uuid, processingReport.uuid);
    }

    @Override
    public int hashCode() {
        return Objects.hash(ellapsedTimeInSeconds, endIsoDateTime, errors, infos, running, startIsoDateTime,
                totalTimeInSeconds, type, uuid);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ProcessingReport {\n");

        sb.append("    ellapsedTimeInSeconds: ").append(toIndentedString(ellapsedTimeInSeconds)).append("\n");
        sb.append("    endIsoDateTime: ").append(toIndentedString(endIsoDateTime)).append("\n");
        sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
        sb.append("    infos: ").append(toIndentedString(infos)).append("\n");
        sb.append("    running: ").append(toIndentedString(running)).append("\n");
        sb.append("    startIsoDateTime: ").append(toIndentedString(startIsoDateTime)).append("\n");
        sb.append("    totalTimeInSeconds: ").append(toIndentedString(totalTimeInSeconds)).append("\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
