/*
 * GeoNetwork Api Documentation (beta)
 * Learn how to access the catalog using the GeoNetwork REST API.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.fao.geonet.openapi.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * RelatedResponse
 */

public class RelatedResponse {
    @JsonProperty("associated")
    private Associated associated = null;

    @JsonProperty("children")
    private Children children = null;

    @JsonProperty("datasets")
    private Dataset datasets = null;

    @JsonProperty("fcats")
    private Fcat fcats = null;

    @JsonProperty("hasfeaturecats")
    private Hasfeaturecats hasfeaturecats = null;

    @JsonProperty("hassources")
    private Hassource hassources = null;

    @JsonProperty("onlines")
    private Online onlines = null;

    @JsonProperty("parent")
    private Parent parent = null;

    @JsonProperty("related")
    private Related related = null;

    @JsonProperty("services")
    private Service services = null;

    @JsonProperty("siblings")
    private Siblings siblings = null;

    @JsonProperty("sources")
    private Source sources = null;

    @JsonProperty("thumbnails")
    private Thumbnail thumbnails = null;

    public RelatedResponse associated(Associated associated) {
        this.associated = associated;
        return this;
    }

    /**
     * Get associated
     * 
     * @return associated
     **/
    @ApiModelProperty(value = "")
    public Associated getAssociated() {
        return associated;
    }

    public void setAssociated(Associated associated) {
        this.associated = associated;
    }

    public RelatedResponse children(Children children) {
        this.children = children;
        return this;
    }

    /**
     * Get children
     * 
     * @return children
     **/
    @ApiModelProperty(value = "")
    public Children getChildren() {
        return children;
    }

    public void setChildren(Children children) {
        this.children = children;
    }

    public RelatedResponse datasets(Dataset datasets) {
        this.datasets = datasets;
        return this;
    }

    /**
     * Get datasets
     * 
     * @return datasets
     **/
    @ApiModelProperty(value = "")
    public Dataset getDatasets() {
        return datasets;
    }

    public void setDatasets(Dataset datasets) {
        this.datasets = datasets;
    }

    public RelatedResponse fcats(Fcat fcats) {
        this.fcats = fcats;
        return this;
    }

    /**
     * Get fcats
     * 
     * @return fcats
     **/
    @ApiModelProperty(value = "")
    public Fcat getFcats() {
        return fcats;
    }

    public void setFcats(Fcat fcats) {
        this.fcats = fcats;
    }

    public RelatedResponse hasfeaturecats(Hasfeaturecats hasfeaturecats) {
        this.hasfeaturecats = hasfeaturecats;
        return this;
    }

    /**
     * Get hasfeaturecats
     * 
     * @return hasfeaturecats
     **/
    @ApiModelProperty(value = "")
    public Hasfeaturecats getHasfeaturecats() {
        return hasfeaturecats;
    }

    public void setHasfeaturecats(Hasfeaturecats hasfeaturecats) {
        this.hasfeaturecats = hasfeaturecats;
    }

    public RelatedResponse hassources(Hassource hassources) {
        this.hassources = hassources;
        return this;
    }

    /**
     * Get hassources
     * 
     * @return hassources
     **/
    @ApiModelProperty(value = "")
    public Hassource getHassources() {
        return hassources;
    }

    public void setHassources(Hassource hassources) {
        this.hassources = hassources;
    }

    public RelatedResponse onlines(Online onlines) {
        this.onlines = onlines;
        return this;
    }

    /**
     * Get onlines
     * 
     * @return onlines
     **/
    @ApiModelProperty(value = "")
    public Online getOnlines() {
        return onlines;
    }

    public void setOnlines(Online onlines) {
        this.onlines = onlines;
    }

    public RelatedResponse parent(Parent parent) {
        this.parent = parent;
        return this;
    }

    /**
     * Get parent
     * 
     * @return parent
     **/
    @ApiModelProperty(value = "")
    public Parent getParent() {
        return parent;
    }

    public void setParent(Parent parent) {
        this.parent = parent;
    }

    public RelatedResponse related(Related related) {
        this.related = related;
        return this;
    }

    /**
     * Get related
     * 
     * @return related
     **/
    @ApiModelProperty(value = "")
    public Related getRelated() {
        return related;
    }

    public void setRelated(Related related) {
        this.related = related;
    }

    public RelatedResponse services(Service services) {
        this.services = services;
        return this;
    }

    /**
     * Get services
     * 
     * @return services
     **/
    @ApiModelProperty(value = "")
    public Service getServices() {
        return services;
    }

    public void setServices(Service services) {
        this.services = services;
    }

    public RelatedResponse siblings(Siblings siblings) {
        this.siblings = siblings;
        return this;
    }

    /**
     * Get siblings
     * 
     * @return siblings
     **/
    @ApiModelProperty(value = "")
    public Siblings getSiblings() {
        return siblings;
    }

    public void setSiblings(Siblings siblings) {
        this.siblings = siblings;
    }

    public RelatedResponse sources(Source sources) {
        this.sources = sources;
        return this;
    }

    /**
     * Get sources
     * 
     * @return sources
     **/
    @ApiModelProperty(value = "")
    public Source getSources() {
        return sources;
    }

    public void setSources(Source sources) {
        this.sources = sources;
    }

    public RelatedResponse thumbnails(Thumbnail thumbnails) {
        this.thumbnails = thumbnails;
        return this;
    }

    /**
     * Get thumbnails
     * 
     * @return thumbnails
     **/
    @ApiModelProperty(value = "")
    public Thumbnail getThumbnails() {
        return thumbnails;
    }

    public void setThumbnails(Thumbnail thumbnails) {
        this.thumbnails = thumbnails;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        RelatedResponse relatedResponse = (RelatedResponse) o;
        return Objects.equals(this.associated, relatedResponse.associated)
                && Objects.equals(this.children, relatedResponse.children)
                && Objects.equals(this.datasets, relatedResponse.datasets)
                && Objects.equals(this.fcats, relatedResponse.fcats)
                && Objects.equals(this.hasfeaturecats, relatedResponse.hasfeaturecats)
                && Objects.equals(this.hassources, relatedResponse.hassources)
                && Objects.equals(this.onlines, relatedResponse.onlines)
                && Objects.equals(this.parent, relatedResponse.parent)
                && Objects.equals(this.related, relatedResponse.related)
                && Objects.equals(this.services, relatedResponse.services)
                && Objects.equals(this.siblings, relatedResponse.siblings)
                && Objects.equals(this.sources, relatedResponse.sources)
                && Objects.equals(this.thumbnails, relatedResponse.thumbnails);
    }

    @Override
    public int hashCode() {
        return Objects.hash(associated, children, datasets, fcats, hasfeaturecats, hassources, onlines, parent, related,
                services, siblings, sources, thumbnails);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class RelatedResponse {\n");

        sb.append("    associated: ").append(toIndentedString(associated)).append("\n");
        sb.append("    children: ").append(toIndentedString(children)).append("\n");
        sb.append("    datasets: ").append(toIndentedString(datasets)).append("\n");
        sb.append("    fcats: ").append(toIndentedString(fcats)).append("\n");
        sb.append("    hasfeaturecats: ").append(toIndentedString(hasfeaturecats)).append("\n");
        sb.append("    hassources: ").append(toIndentedString(hassources)).append("\n");
        sb.append("    onlines: ").append(toIndentedString(onlines)).append("\n");
        sb.append("    parent: ").append(toIndentedString(parent)).append("\n");
        sb.append("    related: ").append(toIndentedString(related)).append("\n");
        sb.append("    services: ").append(toIndentedString(services)).append("\n");
        sb.append("    siblings: ").append(toIndentedString(siblings)).append("\n");
        sb.append("    sources: ").append(toIndentedString(sources)).append("\n");
        sb.append("    thumbnails: ").append(toIndentedString(thumbnails)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
