/*
 * GeoNetwork Api Documentation (beta)
 * Learn how to access the catalog using the GeoNetwork REST API.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.fao.geonet.openapi.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * RelatedSiblingMetadataItem
 */

public class RelatedSiblingMetadataItem {
    @JsonProperty("associationType")
    private String associationType = null;

    @JsonProperty("description")
    private Description description = null;

    @JsonProperty("id")
    private String id = null;

    @JsonProperty("initiativeType")
    private String initiativeType = null;

    @JsonProperty("mdType")
    private List<String> mdType = null;

    @JsonProperty("title")
    private MultilingualValue title = null;

    @JsonProperty("type")
    private String type = null;

    @JsonProperty("url")
    private MultilingualValue url = null;

    public RelatedSiblingMetadataItem associationType(String associationType) {
        this.associationType = associationType;
        return this;
    }

    /**
     * Get associationType
     * 
     * @return associationType
     **/
    @ApiModelProperty(value = "")
    public String getAssociationType() {
        return associationType;
    }

    public void setAssociationType(String associationType) {
        this.associationType = associationType;
    }

    public RelatedSiblingMetadataItem description(Description description) {
        this.description = description;
        return this;
    }

    /**
     * Get description
     * 
     * @return description
     **/
    @ApiModelProperty(value = "")
    public Description getDescription() {
        return description;
    }

    public void setDescription(Description description) {
        this.description = description;
    }

    public RelatedSiblingMetadataItem id(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     * 
     * @return id
     **/
    @ApiModelProperty(value = "")
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public RelatedSiblingMetadataItem initiativeType(String initiativeType) {
        this.initiativeType = initiativeType;
        return this;
    }

    /**
     * Get initiativeType
     * 
     * @return initiativeType
     **/
    @ApiModelProperty(value = "")
    public String getInitiativeType() {
        return initiativeType;
    }

    public void setInitiativeType(String initiativeType) {
        this.initiativeType = initiativeType;
    }

    public RelatedSiblingMetadataItem mdType(List<String> mdType) {
        this.mdType = mdType;
        return this;
    }

    public RelatedSiblingMetadataItem addMdTypeItem(String mdTypeItem) {
        if (this.mdType == null) {
            this.mdType = new ArrayList<>();
        }
        this.mdType.add(mdTypeItem);
        return this;
    }

    /**
     * Get mdType
     * 
     * @return mdType
     **/
    @ApiModelProperty(value = "")
    public List<String> getMdType() {
        return mdType;
    }

    public void setMdType(List<String> mdType) {
        this.mdType = mdType;
    }

    public RelatedSiblingMetadataItem title(MultilingualValue title) {
        this.title = title;
        return this;
    }

    /**
     * Get title
     * 
     * @return title
     **/
    @ApiModelProperty(value = "")
    public MultilingualValue getTitle() {
        return title;
    }

    public void setTitle(MultilingualValue title) {
        this.title = title;
    }

    public RelatedSiblingMetadataItem type(String type) {
        this.type = type;
        return this;
    }

    /**
     * Get type
     * 
     * @return type
     **/
    @ApiModelProperty(value = "")
    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public RelatedSiblingMetadataItem url(MultilingualValue url) {
        this.url = url;
        return this;
    }

    /**
     * Get url
     * 
     * @return url
     **/
    @ApiModelProperty(value = "")
    public MultilingualValue getUrl() {
        return url;
    }

    public void setUrl(MultilingualValue url) {
        this.url = url;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        RelatedSiblingMetadataItem relatedSiblingMetadataItem = (RelatedSiblingMetadataItem) o;
        return Objects.equals(this.associationType, relatedSiblingMetadataItem.associationType)
                && Objects.equals(this.description, relatedSiblingMetadataItem.description)
                && Objects.equals(this.id, relatedSiblingMetadataItem.id)
                && Objects.equals(this.initiativeType, relatedSiblingMetadataItem.initiativeType)
                && Objects.equals(this.mdType, relatedSiblingMetadataItem.mdType)
                && Objects.equals(this.title, relatedSiblingMetadataItem.title)
                && Objects.equals(this.type, relatedSiblingMetadataItem.type)
                && Objects.equals(this.url, relatedSiblingMetadataItem.url);
    }

    @Override
    public int hashCode() {
        return Objects.hash(associationType, description, id, initiativeType, mdType, title, type, url);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class RelatedSiblingMetadataItem {\n");

        sb.append("    associationType: ").append(toIndentedString(associationType)).append("\n");
        sb.append("    description: ").append(toIndentedString(description)).append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    initiativeType: ").append(toIndentedString(initiativeType)).append("\n");
        sb.append("    mdType: ").append(toIndentedString(mdType)).append("\n");
        sb.append("    title: ").append(toIndentedString(title)).append("\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("    url: ").append(toIndentedString(url)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
