/*
 * GeoNetwork Api Documentation (beta)
 * Learn how to access the catalog using the GeoNetwork REST API.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.fao.geonet.openapi.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * RelatedThumbnailItem
 */

public class RelatedThumbnailItem {
    @JsonProperty("id")
    private String id = null;

    @JsonProperty("title")
    private MultilingualValue title = null;

    @JsonProperty("type")
    private String type = null;

    @JsonProperty("url")
    private MultilingualValue url = null;

    public RelatedThumbnailItem id(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     * 
     * @return id
     **/
    @ApiModelProperty(value = "")
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public RelatedThumbnailItem title(MultilingualValue title) {
        this.title = title;
        return this;
    }

    /**
     * Get title
     * 
     * @return title
     **/
    @ApiModelProperty(value = "")
    public MultilingualValue getTitle() {
        return title;
    }

    public void setTitle(MultilingualValue title) {
        this.title = title;
    }

    public RelatedThumbnailItem type(String type) {
        this.type = type;
        return this;
    }

    /**
     * Get type
     * 
     * @return type
     **/
    @ApiModelProperty(value = "")
    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public RelatedThumbnailItem url(MultilingualValue url) {
        this.url = url;
        return this;
    }

    /**
     * Get url
     * 
     * @return url
     **/
    @ApiModelProperty(value = "")
    public MultilingualValue getUrl() {
        return url;
    }

    public void setUrl(MultilingualValue url) {
        this.url = url;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        RelatedThumbnailItem relatedThumbnailItem = (RelatedThumbnailItem) o;
        return Objects.equals(this.id, relatedThumbnailItem.id)
                && Objects.equals(this.title, relatedThumbnailItem.title)
                && Objects.equals(this.type, relatedThumbnailItem.type)
                && Objects.equals(this.url, relatedThumbnailItem.url);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, title, type, url);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class RelatedThumbnailItem {\n");

        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    title: ").append(toIndentedString(title)).append("\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("    url: ").append(toIndentedString(url)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
