/*
 * GeoNetwork Api Documentation (beta)
 * Learn how to access the catalog using the GeoNetwork REST API.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.fao.geonet.openapi.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * ReplaceEntryChange
 */

public class ReplaceEntryChange {
    @JsonProperty("changedVal")
    private String changedVal = null;

    @JsonProperty("fieldId")
    private String fieldId = null;

    @JsonProperty("originalVal")
    private String originalVal = null;

    public ReplaceEntryChange changedVal(String changedVal) {
        this.changedVal = changedVal;
        return this;
    }

    /**
     * Get changedVal
     * 
     * @return changedVal
     **/
    @ApiModelProperty(value = "")
    public String getChangedVal() {
        return changedVal;
    }

    public void setChangedVal(String changedVal) {
        this.changedVal = changedVal;
    }

    public ReplaceEntryChange fieldId(String fieldId) {
        this.fieldId = fieldId;
        return this;
    }

    /**
     * Get fieldId
     * 
     * @return fieldId
     **/
    @ApiModelProperty(value = "")
    public String getFieldId() {
        return fieldId;
    }

    public void setFieldId(String fieldId) {
        this.fieldId = fieldId;
    }

    public ReplaceEntryChange originalVal(String originalVal) {
        this.originalVal = originalVal;
        return this;
    }

    /**
     * Get originalVal
     * 
     * @return originalVal
     **/
    @ApiModelProperty(value = "")
    public String getOriginalVal() {
        return originalVal;
    }

    public void setOriginalVal(String originalVal) {
        this.originalVal = originalVal;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ReplaceEntryChange replaceEntryChange = (ReplaceEntryChange) o;
        return Objects.equals(this.changedVal, replaceEntryChange.changedVal)
                && Objects.equals(this.fieldId, replaceEntryChange.fieldId)
                && Objects.equals(this.originalVal, replaceEntryChange.originalVal);
    }

    @Override
    public int hashCode() {
        return Objects.hash(changedVal, fieldId, originalVal);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ReplaceEntryChange {\n");

        sb.append("    changedVal: ").append(toIndentedString(changedVal)).append("\n");
        sb.append("    fieldId: ").append(toIndentedString(fieldId)).append("\n");
        sb.append("    originalVal: ").append(toIndentedString(originalVal)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
