/*
 * GeoNetwork Api Documentation (beta)
 * Learn how to access the catalog using the GeoNetwork REST API.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.fao.geonet.openapi.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;

import io.swagger.annotations.ApiModelProperty;

/**
 * ResponseEntity
 */

public class ResponseEntity {
    @JsonProperty("body")
    private Object body = null;

    /**
     * Gets or Sets statusCode
     */
    public enum StatusCodeEnum {
        _100("100"),

        _101("101"),

        _102("102"),

        _103("103"),

        _200("200"),

        _201("201"),

        _202("202"),

        _203("203"),

        _204("204"),

        _205("205"),

        _206("206"),

        _207("207"),

        _208("208"),

        _226("226"),

        _300("300"),

        _301("301"),

        _302("302"),

        _303("303"),

        _304("304"),

        _305("305"),

        _307("307"),

        _308("308"),

        _400("400"),

        _401("401"),

        _402("402"),

        _403("403"),

        _404("404"),

        _405("405"),

        _406("406"),

        _407("407"),

        _408("408"),

        _409("409"),

        _410("410"),

        _411("411"),

        _412("412"),

        _413("413"),

        _414("414"),

        _415("415"),

        _416("416"),

        _417("417"),

        _418("418"),

        _419("419"),

        _420("420"),

        _421("421"),

        _422("422"),

        _423("423"),

        _424("424"),

        _426("426"),

        _428("428"),

        _429("429"),

        _431("431"),

        _500("500"),

        _501("501"),

        _502("502"),

        _503("503"),

        _504("504"),

        _505("505"),

        _506("506"),

        _507("507"),

        _508("508"),

        _509("509"),

        _510("510"),

        _511("511");

        private String value;

        StatusCodeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        @JsonCreator
        public static StatusCodeEnum fromValue(String text) {
            for (StatusCodeEnum b : StatusCodeEnum.values()) {
                if (String.valueOf(b.value).equals(text)) {
                    return b;
                }
            }
            return null;
        }
    }

    @JsonProperty("statusCode")
    private StatusCodeEnum statusCode = null;

    public ResponseEntity body(Object body) {
        this.body = body;
        return this;
    }

    /**
     * Get body
     * 
     * @return body
     **/
    @ApiModelProperty(value = "")
    public Object getBody() {
        return body;
    }

    public void setBody(Object body) {
        this.body = body;
    }

    public ResponseEntity statusCode(StatusCodeEnum statusCode) {
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Get statusCode
     * 
     * @return statusCode
     **/
    @ApiModelProperty(value = "")
    public StatusCodeEnum getStatusCode() {
        return statusCode;
    }

    public void setStatusCode(StatusCodeEnum statusCode) {
        this.statusCode = statusCode;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ResponseEntity responseEntity = (ResponseEntity) o;
        return Objects.equals(this.body, responseEntity.body)
                && Objects.equals(this.statusCode, responseEntity.statusCode);
    }

    @Override
    public int hashCode() {
        return Objects.hash(body, statusCode);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ResponseEntity {\n");

        sb.append("    body: ").append(toIndentedString(body)).append("\n");
        sb.append("    statusCode: ").append(toIndentedString(statusCode)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
