/*
 * GeoNetwork Api Documentation (beta)
 * Learn how to access the catalog using the GeoNetwork REST API.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.fao.geonet.openapi.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * Rule
 */

public class Rule {
    @JsonProperty("details")
    private String details = null;

    @JsonProperty("group")
    private String group = null;

    @JsonProperty("id")
    private String id = null;

    @JsonProperty("msg")
    private String msg = null;

    @JsonProperty("ref")
    private String ref = null;

    @JsonProperty("test")
    private String test = null;

    @JsonProperty("type")
    private String type = null;

    public Rule details(String details) {
        this.details = details;
        return this;
    }

    /**
     * Get details
     * 
     * @return details
     **/
    @ApiModelProperty(value = "")
    public String getDetails() {
        return details;
    }

    public void setDetails(String details) {
        this.details = details;
    }

    public Rule group(String group) {
        this.group = group;
        return this;
    }

    /**
     * Get group
     * 
     * @return group
     **/
    @ApiModelProperty(value = "")
    public String getGroup() {
        return group;
    }

    public void setGroup(String group) {
        this.group = group;
    }

    public Rule id(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     * 
     * @return id
     **/
    @ApiModelProperty(value = "")
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Rule msg(String msg) {
        this.msg = msg;
        return this;
    }

    /**
     * Get msg
     * 
     * @return msg
     **/
    @ApiModelProperty(value = "")
    public String getMsg() {
        return msg;
    }

    public void setMsg(String msg) {
        this.msg = msg;
    }

    public Rule ref(String ref) {
        this.ref = ref;
        return this;
    }

    /**
     * Get ref
     * 
     * @return ref
     **/
    @ApiModelProperty(value = "")
    public String getRef() {
        return ref;
    }

    public void setRef(String ref) {
        this.ref = ref;
    }

    public Rule test(String test) {
        this.test = test;
        return this;
    }

    /**
     * Get test
     * 
     * @return test
     **/
    @ApiModelProperty(value = "")
    public String getTest() {
        return test;
    }

    public void setTest(String test) {
        this.test = test;
    }

    public Rule type(String type) {
        this.type = type;
        return this;
    }

    /**
     * Get type
     * 
     * @return type
     **/
    @ApiModelProperty(value = "")
    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Rule rule = (Rule) o;
        return Objects.equals(this.details, rule.details) && Objects.equals(this.group, rule.group)
                && Objects.equals(this.id, rule.id) && Objects.equals(this.msg, rule.msg)
                && Objects.equals(this.ref, rule.ref) && Objects.equals(this.test, rule.test)
                && Objects.equals(this.type, rule.type);
    }

    @Override
    public int hashCode() {
        return Objects.hash(details, group, id, msg, ref, test, type);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Rule {\n");

        sb.append("    details: ").append(toIndentedString(details)).append("\n");
        sb.append("    group: ").append(toIndentedString(group)).append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    msg: ").append(toIndentedString(msg)).append("\n");
        sb.append("    ref: ").append(toIndentedString(ref)).append("\n");
        sb.append("    test: ").append(toIndentedString(test)).append("\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
