/*
 * GeoNetwork Api Documentation (beta)
 * Learn how to access the catalog using the GeoNetwork REST API.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.fao.geonet.openapi.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * SavedQuery
 */

public class SavedQuery {
    @JsonProperty("cleanValues")
    private String cleanValues = null;

    @JsonProperty("id")
    private String id = null;

    @JsonProperty("label")
    private String label = null;

    @JsonProperty("parameters")
    private List<String> parameters = null;

    @JsonProperty("xpath")
    private String xpath = null;

    public SavedQuery cleanValues(String cleanValues) {
        this.cleanValues = cleanValues;
        return this;
    }

    /**
     * Get cleanValues
     * 
     * @return cleanValues
     **/
    @ApiModelProperty(value = "")
    public String getCleanValues() {
        return cleanValues;
    }

    public void setCleanValues(String cleanValues) {
        this.cleanValues = cleanValues;
    }

    public SavedQuery id(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     * 
     * @return id
     **/
    @ApiModelProperty(value = "")
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public SavedQuery label(String label) {
        this.label = label;
        return this;
    }

    /**
     * Get label
     * 
     * @return label
     **/
    @ApiModelProperty(value = "")
    public String getLabel() {
        return label;
    }

    public void setLabel(String label) {
        this.label = label;
    }

    public SavedQuery parameters(List<String> parameters) {
        this.parameters = parameters;
        return this;
    }

    public SavedQuery addParametersItem(String parametersItem) {
        if (this.parameters == null) {
            this.parameters = new ArrayList<>();
        }
        this.parameters.add(parametersItem);
        return this;
    }

    /**
     * Get parameters
     * 
     * @return parameters
     **/
    @ApiModelProperty(value = "")
    public List<String> getParameters() {
        return parameters;
    }

    public void setParameters(List<String> parameters) {
        this.parameters = parameters;
    }

    public SavedQuery xpath(String xpath) {
        this.xpath = xpath;
        return this;
    }

    /**
     * Get xpath
     * 
     * @return xpath
     **/
    @ApiModelProperty(value = "")
    public String getXpath() {
        return xpath;
    }

    public void setXpath(String xpath) {
        this.xpath = xpath;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SavedQuery savedQuery = (SavedQuery) o;
        return Objects.equals(this.cleanValues, savedQuery.cleanValues) && Objects.equals(this.id, savedQuery.id)
                && Objects.equals(this.label, savedQuery.label)
                && Objects.equals(this.parameters, savedQuery.parameters)
                && Objects.equals(this.xpath, savedQuery.xpath);
    }

    @Override
    public int hashCode() {
        return Objects.hash(cleanValues, id, label, parameters, xpath);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class SavedQuery {\n");

        sb.append("    cleanValues: ").append(toIndentedString(cleanValues)).append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    label: ").append(toIndentedString(label)).append("\n");
        sb.append("    parameters: ").append(toIndentedString(parameters)).append("\n");
        sb.append("    xpath: ").append(toIndentedString(xpath)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
