/*
 * GeoNetwork Api Documentation (beta)
 * Learn how to access the catalog using the GeoNetwork REST API.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.fao.geonet.openapi.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * SharingParameter
 */

public class SharingParameter {
    @JsonProperty("clear")
    private Boolean clear = null;

    @JsonProperty("privileges")
    private List<GroupOperations> privileges = null;

    public SharingParameter clear(Boolean clear) {
        this.clear = clear;
        return this;
    }

    /**
     * Get clear
     * 
     * @return clear
     **/
    @ApiModelProperty(value = "")
    public Boolean isClear() {
        return clear;
    }

    public void setClear(Boolean clear) {
        this.clear = clear;
    }

    public SharingParameter privileges(List<GroupOperations> privileges) {
        this.privileges = privileges;
        return this;
    }

    public SharingParameter addPrivilegesItem(GroupOperations privilegesItem) {
        if (this.privileges == null) {
            this.privileges = new ArrayList<>();
        }
        this.privileges.add(privilegesItem);
        return this;
    }

    /**
     * Get privileges
     * 
     * @return privileges
     **/
    @ApiModelProperty(value = "")
    public List<GroupOperations> getPrivileges() {
        return privileges;
    }

    public void setPrivileges(List<GroupOperations> privileges) {
        this.privileges = privileges;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SharingParameter sharingParameter = (SharingParameter) o;
        return Objects.equals(this.clear, sharingParameter.clear)
                && Objects.equals(this.privileges, sharingParameter.privileges);
    }

    @Override
    public int hashCode() {
        return Objects.hash(clear, privileges);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class SharingParameter {\n");

        sb.append("    clear: ").append(toIndentedString(clear)).append("\n");
        sb.append("    privileges: ").append(toIndentedString(privileges)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
