/*
 * GeoNetwork Api Documentation (beta)
 * Learn how to access the catalog using the GeoNetwork REST API.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.fao.geonet.openapi.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * SharingResponse
 */

public class SharingResponse {
    @JsonProperty("groupOwner")
    private String groupOwner = null;

    @JsonProperty("owner")
    private String owner = null;

    @JsonProperty("privileges")
    private List<GroupPrivilege> privileges = null;

    public SharingResponse groupOwner(String groupOwner) {
        this.groupOwner = groupOwner;
        return this;
    }

    /**
     * Get groupOwner
     * 
     * @return groupOwner
     **/
    @ApiModelProperty(value = "")
    public String getGroupOwner() {
        return groupOwner;
    }

    public void setGroupOwner(String groupOwner) {
        this.groupOwner = groupOwner;
    }

    public SharingResponse owner(String owner) {
        this.owner = owner;
        return this;
    }

    /**
     * Get owner
     * 
     * @return owner
     **/
    @ApiModelProperty(value = "")
    public String getOwner() {
        return owner;
    }

    public void setOwner(String owner) {
        this.owner = owner;
    }

    public SharingResponse privileges(List<GroupPrivilege> privileges) {
        this.privileges = privileges;
        return this;
    }

    public SharingResponse addPrivilegesItem(GroupPrivilege privilegesItem) {
        if (this.privileges == null) {
            this.privileges = new ArrayList<>();
        }
        this.privileges.add(privilegesItem);
        return this;
    }

    /**
     * Get privileges
     * 
     * @return privileges
     **/
    @ApiModelProperty(value = "")
    public List<GroupPrivilege> getPrivileges() {
        return privileges;
    }

    public void setPrivileges(List<GroupPrivilege> privileges) {
        this.privileges = privileges;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SharingResponse sharingResponse = (SharingResponse) o;
        return Objects.equals(this.groupOwner, sharingResponse.groupOwner)
                && Objects.equals(this.owner, sharingResponse.owner)
                && Objects.equals(this.privileges, sharingResponse.privileges);
    }

    @Override
    public int hashCode() {
        return Objects.hash(groupOwner, owner, privileges);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class SharingResponse {\n");

        sb.append("    groupOwner: ").append(toIndentedString(groupOwner)).append("\n");
        sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
        sb.append("    privileges: ").append(toIndentedString(privileges)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
