/*
 * GeoNetwork Api Documentation (beta)
 * Learn how to access the catalog using the GeoNetwork REST API.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.fao.geonet.openapi.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * SuggestionType
 */

public class SuggestionType {
    @JsonProperty("category")
    private String category = null;

    @JsonProperty("id")
    private String id = null;

    @JsonProperty("name")
    private String name = null;

    @JsonProperty("operational")
    private String operational = null;

    @JsonProperty("params")
    private String params = null;

    @JsonProperty("process")
    private String process = null;

    @JsonProperty("target")
    private String target = null;

    public SuggestionType category(String category) {
        this.category = category;
        return this;
    }

    /**
     * Get category
     * 
     * @return category
     **/
    @ApiModelProperty(value = "")
    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public SuggestionType id(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     * 
     * @return id
     **/
    @ApiModelProperty(value = "")
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public SuggestionType name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get name
     * 
     * @return name
     **/
    @ApiModelProperty(value = "")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public SuggestionType operational(String operational) {
        this.operational = operational;
        return this;
    }

    /**
     * Get operational
     * 
     * @return operational
     **/
    @ApiModelProperty(value = "")
    public String getOperational() {
        return operational;
    }

    public void setOperational(String operational) {
        this.operational = operational;
    }

    public SuggestionType params(String params) {
        this.params = params;
        return this;
    }

    /**
     * Get params
     * 
     * @return params
     **/
    @ApiModelProperty(value = "")
    public String getParams() {
        return params;
    }

    public void setParams(String params) {
        this.params = params;
    }

    public SuggestionType process(String process) {
        this.process = process;
        return this;
    }

    /**
     * Get process
     * 
     * @return process
     **/
    @ApiModelProperty(value = "")
    public String getProcess() {
        return process;
    }

    public void setProcess(String process) {
        this.process = process;
    }

    public SuggestionType target(String target) {
        this.target = target;
        return this;
    }

    /**
     * Get target
     * 
     * @return target
     **/
    @ApiModelProperty(value = "")
    public String getTarget() {
        return target;
    }

    public void setTarget(String target) {
        this.target = target;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SuggestionType suggestionType = (SuggestionType) o;
        return Objects.equals(this.category, suggestionType.category) && Objects.equals(this.id, suggestionType.id)
                && Objects.equals(this.name, suggestionType.name)
                && Objects.equals(this.operational, suggestionType.operational)
                && Objects.equals(this.params, suggestionType.params)
                && Objects.equals(this.process, suggestionType.process)
                && Objects.equals(this.target, suggestionType.target);
    }

    @Override
    public int hashCode() {
        return Objects.hash(category, id, name, operational, params, process, target);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class SuggestionType {\n");

        sb.append("    category: ").append(toIndentedString(category)).append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    operational: ").append(toIndentedString(operational)).append("\n");
        sb.append("    params: ").append(toIndentedString(params)).append("\n");
        sb.append("    process: ").append(toIndentedString(process)).append("\n");
        sb.append("    target: ").append(toIndentedString(target)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
