/*
 * GeoNetwork Api Documentation (beta)
 * Learn how to access the catalog using the GeoNetwork REST API.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.fao.geonet.openapi.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * TransferRequest
 */

public class TransferRequest {
    @JsonProperty("sourceGroup")
    private Integer sourceGroup = null;

    @JsonProperty("sourceUser")
    private Integer sourceUser = null;

    @JsonProperty("targetGroup")
    private Integer targetGroup = null;

    @JsonProperty("targetUser")
    private Integer targetUser = null;

    public TransferRequest sourceGroup(Integer sourceGroup) {
        this.sourceGroup = sourceGroup;
        return this;
    }

    /**
     * Get sourceGroup
     * 
     * @return sourceGroup
     **/
    @ApiModelProperty(value = "")
    public Integer getSourceGroup() {
        return sourceGroup;
    }

    public void setSourceGroup(Integer sourceGroup) {
        this.sourceGroup = sourceGroup;
    }

    public TransferRequest sourceUser(Integer sourceUser) {
        this.sourceUser = sourceUser;
        return this;
    }

    /**
     * Get sourceUser
     * 
     * @return sourceUser
     **/
    @ApiModelProperty(value = "")
    public Integer getSourceUser() {
        return sourceUser;
    }

    public void setSourceUser(Integer sourceUser) {
        this.sourceUser = sourceUser;
    }

    public TransferRequest targetGroup(Integer targetGroup) {
        this.targetGroup = targetGroup;
        return this;
    }

    /**
     * Get targetGroup
     * 
     * @return targetGroup
     **/
    @ApiModelProperty(value = "")
    public Integer getTargetGroup() {
        return targetGroup;
    }

    public void setTargetGroup(Integer targetGroup) {
        this.targetGroup = targetGroup;
    }

    public TransferRequest targetUser(Integer targetUser) {
        this.targetUser = targetUser;
        return this;
    }

    /**
     * Get targetUser
     * 
     * @return targetUser
     **/
    @ApiModelProperty(value = "")
    public Integer getTargetUser() {
        return targetUser;
    }

    public void setTargetUser(Integer targetUser) {
        this.targetUser = targetUser;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TransferRequest transferRequest = (TransferRequest) o;
        return Objects.equals(this.sourceGroup, transferRequest.sourceGroup)
                && Objects.equals(this.sourceUser, transferRequest.sourceUser)
                && Objects.equals(this.targetGroup, transferRequest.targetGroup)
                && Objects.equals(this.targetUser, transferRequest.targetUser);
    }

    @Override
    public int hashCode() {
        return Objects.hash(sourceGroup, sourceUser, targetGroup, targetUser);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class TransferRequest {\n");

        sb.append("    sourceGroup: ").append(toIndentedString(sourceGroup)).append("\n");
        sb.append("    sourceUser: ").append(toIndentedString(sourceUser)).append("\n");
        sb.append("    targetGroup: ").append(toIndentedString(targetGroup)).append("\n");
        sb.append("    targetUser: ").append(toIndentedString(targetUser)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
