/*
 * GeoNetwork Api Documentation (beta)
 * Learn how to access the catalog using the GeoNetwork REST API.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.fao.geonet.openapi.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;

import io.swagger.annotations.ApiModelProperty;

/**
 * UserGroup
 */

public class UserGroup {
    @JsonProperty("group")
    private Group group = null;

    @JsonProperty("id")
    private UserGroupId id = null;

    /**
     * Gets or Sets profile
     */
    public enum ProfileEnum {
        ADMINISTRATOR("Administrator"),

        USERADMIN("UserAdmin"),

        REVIEWER("Reviewer"),

        EDITOR("Editor"),

        REGISTEREDUSER("RegisteredUser"),

        GUEST("Guest"),

        MONITOR("Monitor");

        private String value;

        ProfileEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        @JsonCreator
        public static ProfileEnum fromValue(String text) {
            for (ProfileEnum b : ProfileEnum.values()) {
                if (String.valueOf(b.value).equals(text)) {
                    return b;
                }
            }
            return null;
        }
    }

    @JsonProperty("profile")
    private ProfileEnum profile = null;

    @JsonProperty("user")
    private User user = null;

    public UserGroup group(Group group) {
        this.group = group;
        return this;
    }

    /**
     * Get group
     * 
     * @return group
     **/
    @ApiModelProperty(value = "")
    public Group getGroup() {
        return group;
    }

    public void setGroup(Group group) {
        this.group = group;
    }

    public UserGroup id(UserGroupId id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     * 
     * @return id
     **/
    @ApiModelProperty(value = "")
    public UserGroupId getId() {
        return id;
    }

    public void setId(UserGroupId id) {
        this.id = id;
    }

    public UserGroup profile(ProfileEnum profile) {
        this.profile = profile;
        return this;
    }

    /**
     * Get profile
     * 
     * @return profile
     **/
    @ApiModelProperty(value = "")
    public ProfileEnum getProfile() {
        return profile;
    }

    public void setProfile(ProfileEnum profile) {
        this.profile = profile;
    }

    public UserGroup user(User user) {
        this.user = user;
        return this;
    }

    /**
     * Get user
     * 
     * @return user
     **/
    @ApiModelProperty(value = "")
    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UserGroup userGroup = (UserGroup) o;
        return Objects.equals(this.group, userGroup.group) && Objects.equals(this.id, userGroup.id)
                && Objects.equals(this.profile, userGroup.profile) && Objects.equals(this.user, userGroup.user);
    }

    @Override
    public int hashCode() {
        return Objects.hash(group, id, profile, user);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class UserGroup {\n");

        sb.append("    group: ").append(toIndentedString(group)).append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    profile: ").append(toIndentedString(profile)).append("\n");
        sb.append("    user: ").append(toIndentedString(user)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
