/*
 * GeoNetwork Api Documentation (beta)
 * Learn how to access the catalog using the GeoNetwork REST API.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.fao.geonet.openapi.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * UserSearchDto
 */

public class UserSearchDto {
    @JsonProperty("creationDate")
    private String creationDate = null;

    @JsonProperty("creator")
    private String creator = null;

    @JsonProperty("creatorId")
    private Integer creatorId = null;

    @JsonProperty("featuredType")
    private String featuredType = null;

    @JsonProperty("groups")
    private List<Integer> groups = null;

    @JsonProperty("id")
    private Integer id = null;

    @JsonProperty("logo")
    private String logo = null;

    @JsonProperty("names")
    private Map<String, String> names = null;

    @JsonProperty("url")
    private String url = null;

    public UserSearchDto creationDate(String creationDate) {
        this.creationDate = creationDate;
        return this;
    }

    /**
     * Get creationDate
     * 
     * @return creationDate
     **/
    @ApiModelProperty(value = "")
    public String getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(String creationDate) {
        this.creationDate = creationDate;
    }

    public UserSearchDto creator(String creator) {
        this.creator = creator;
        return this;
    }

    /**
     * Get creator
     * 
     * @return creator
     **/
    @ApiModelProperty(value = "")
    public String getCreator() {
        return creator;
    }

    public void setCreator(String creator) {
        this.creator = creator;
    }

    public UserSearchDto creatorId(Integer creatorId) {
        this.creatorId = creatorId;
        return this;
    }

    /**
     * Get creatorId
     * 
     * @return creatorId
     **/
    @ApiModelProperty(value = "")
    public Integer getCreatorId() {
        return creatorId;
    }

    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    public UserSearchDto featuredType(String featuredType) {
        this.featuredType = featuredType;
        return this;
    }

    /**
     * Get featuredType
     * 
     * @return featuredType
     **/
    @ApiModelProperty(value = "")
    public String getFeaturedType() {
        return featuredType;
    }

    public void setFeaturedType(String featuredType) {
        this.featuredType = featuredType;
    }

    public UserSearchDto groups(List<Integer> groups) {
        this.groups = groups;
        return this;
    }

    public UserSearchDto addGroupsItem(Integer groupsItem) {
        if (this.groups == null) {
            this.groups = new ArrayList<>();
        }
        this.groups.add(groupsItem);
        return this;
    }

    /**
     * Get groups
     * 
     * @return groups
     **/
    @ApiModelProperty(value = "")
    public List<Integer> getGroups() {
        return groups;
    }

    public void setGroups(List<Integer> groups) {
        this.groups = groups;
    }

    public UserSearchDto id(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     * 
     * @return id
     **/
    @ApiModelProperty(value = "")
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public UserSearchDto logo(String logo) {
        this.logo = logo;
        return this;
    }

    /**
     * Get logo
     * 
     * @return logo
     **/
    @ApiModelProperty(value = "")
    public String getLogo() {
        return logo;
    }

    public void setLogo(String logo) {
        this.logo = logo;
    }

    public UserSearchDto names(Map<String, String> names) {
        this.names = names;
        return this;
    }

    public UserSearchDto putNamesItem(String key, String namesItem) {
        if (this.names == null) {
            this.names = new HashMap<>();
        }
        this.names.put(key, namesItem);
        return this;
    }

    /**
     * Get names
     * 
     * @return names
     **/
    @ApiModelProperty(value = "")
    public Map<String, String> getNames() {
        return names;
    }

    public void setNames(Map<String, String> names) {
        this.names = names;
    }

    public UserSearchDto url(String url) {
        this.url = url;
        return this;
    }

    /**
     * Get url
     * 
     * @return url
     **/
    @ApiModelProperty(value = "")
    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UserSearchDto userSearchDto = (UserSearchDto) o;
        return Objects.equals(this.creationDate, userSearchDto.creationDate)
                && Objects.equals(this.creator, userSearchDto.creator)
                && Objects.equals(this.creatorId, userSearchDto.creatorId)
                && Objects.equals(this.featuredType, userSearchDto.featuredType)
                && Objects.equals(this.groups, userSearchDto.groups) && Objects.equals(this.id, userSearchDto.id)
                && Objects.equals(this.logo, userSearchDto.logo) && Objects.equals(this.names, userSearchDto.names)
                && Objects.equals(this.url, userSearchDto.url);
    }

    @Override
    public int hashCode() {
        return Objects.hash(creationDate, creator, creatorId, featuredType, groups, id, logo, names, url);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class UserSearchDto {\n");

        sb.append("    creationDate: ").append(toIndentedString(creationDate)).append("\n");
        sb.append("    creator: ").append(toIndentedString(creator)).append("\n");
        sb.append("    creatorId: ").append(toIndentedString(creatorId)).append("\n");
        sb.append("    featuredType: ").append(toIndentedString(featuredType)).append("\n");
        sb.append("    groups: ").append(toIndentedString(groups)).append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    logo: ").append(toIndentedString(logo)).append("\n");
        sb.append("    names: ").append(toIndentedString(names)).append("\n");
        sb.append("    url: ").append(toIndentedString(url)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
