/*
 * GeoNetwork Api Documentation (beta)
 * Learn how to access the catalog using the GeoNetwork REST API.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.fao.geonet.openapi.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * UserGroupsResponse
 */

public class UserGroupsResponse {
    @JsonProperty("groupId")
    private Integer groupId = null;

    @JsonProperty("groupName")
    private String groupName = null;

    @JsonProperty("userId")
    private Integer userId = null;

    @JsonProperty("userName")
    private String userName = null;

    @JsonProperty("userProfile")
    private String userProfile = null;

    public UserGroupsResponse groupId(Integer groupId) {
        this.groupId = groupId;
        return this;
    }

    /**
     * Get groupId
     * 
     * @return groupId
     **/
    @ApiModelProperty(value = "")
    public Integer getGroupId() {
        return groupId;
    }

    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    public UserGroupsResponse groupName(String groupName) {
        this.groupName = groupName;
        return this;
    }

    /**
     * Get groupName
     * 
     * @return groupName
     **/
    @ApiModelProperty(value = "")
    public String getGroupName() {
        return groupName;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    public UserGroupsResponse userId(Integer userId) {
        this.userId = userId;
        return this;
    }

    /**
     * Get userId
     * 
     * @return userId
     **/
    @ApiModelProperty(value = "")
    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public UserGroupsResponse userName(String userName) {
        this.userName = userName;
        return this;
    }

    /**
     * Get userName
     * 
     * @return userName
     **/
    @ApiModelProperty(value = "")
    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public UserGroupsResponse userProfile(String userProfile) {
        this.userProfile = userProfile;
        return this;
    }

    /**
     * Get userProfile
     * 
     * @return userProfile
     **/
    @ApiModelProperty(value = "")
    public String getUserProfile() {
        return userProfile;
    }

    public void setUserProfile(String userProfile) {
        this.userProfile = userProfile;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UserGroupsResponse userGroupsResponse = (UserGroupsResponse) o;
        return Objects.equals(this.groupId, userGroupsResponse.groupId)
                && Objects.equals(this.groupName, userGroupsResponse.groupName)
                && Objects.equals(this.userId, userGroupsResponse.userId)
                && Objects.equals(this.userName, userGroupsResponse.userName)
                && Objects.equals(this.userProfile, userGroupsResponse.userProfile);
    }

    @Override
    public int hashCode() {
        return Objects.hash(groupId, groupName, userId, userName, userProfile);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class UserGroupsResponse {\n");

        sb.append("    groupId: ").append(toIndentedString(groupId)).append("\n");
        sb.append("    groupName: ").append(toIndentedString(groupName)).append("\n");
        sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
        sb.append("    userName: ").append(toIndentedString(userName)).append("\n");
        sb.append("    userProfile: ").append(toIndentedString(userProfile)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
