/*
 * GeoNetwork Api Documentation (beta)
 * Learn how to access the catalog using the GeoNetwork REST API.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.fao.geonet.openapi.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;

/**
 * Values
 */

public class Values {
    @JsonProperty("code")
    private String code = null;

    @JsonProperty("definition")
    private String definition = null;

    @JsonProperty("label")
    private String label = null;

    public Values code(String code) {
        this.code = code;
        return this;
    }

    /**
     * Get code
     * 
     * @return code
     **/
    @ApiModelProperty(value = "")
    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public Values definition(String definition) {
        this.definition = definition;
        return this;
    }

    /**
     * Get definition
     * 
     * @return definition
     **/
    @ApiModelProperty(value = "")
    public String getDefinition() {
        return definition;
    }

    public void setDefinition(String definition) {
        this.definition = definition;
    }

    public Values label(String label) {
        this.label = label;
        return this;
    }

    /**
     * Get label
     * 
     * @return label
     **/
    @ApiModelProperty(value = "")
    public String getLabel() {
        return label;
    }

    public void setLabel(String label) {
        this.label = label;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Values values = (Values) o;
        return Objects.equals(this.code, values.code) && Objects.equals(this.definition, values.definition)
                && Objects.equals(this.label, values.label);
    }

    @Override
    public int hashCode() {
        return Objects.hash(code, definition, label);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Values {\n");

        sb.append("    code: ").append(toIndentedString(code)).append("\n");
        sb.append("    definition: ").append(toIndentedString(definition)).append("\n");
        sb.append("    label: ").append(toIndentedString(label)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
