# Docker composition to run integration tests against.
# Sets up required external services:
version: '3.8'

volumes:
  datafeeder_uploads:

services:
  datafeeder:
    image: georchestra/datafeeder:23.1-SNAPSHOT
    healthcheck:
      test: ["CMD-SHELL", "curl -s -f http://localhost:8080/datafeeder >/dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
    depends_on:
      database:
        condition: service_healthy
      postgis:
        condition: service_healthy
    volumes:
      - ./src/test/resources/datadir:/etc/georchestra
      - datafeeder_uploads:/tmp/datafeeder
    environment:
      - JAVA_OPTS=-Xms512m -Xmx512m
    env_file:
      - .envs-common
      - .envs-hosts
      - .envs-database-georchestra
      - .envs-database-datafeeder
    ports:
      - ${DATAFEEDER_PORT}:8080

