OpenLayers.Util.applyDefaults(OpenLayers.Lang["fr"], {    
      "addonprofile.error": "Erreur sur l'outil profil",
      "addonprofile.impossible": "Pas possible ici",	  
      "addonprofile.refresh": "Actualiser",
	  "addonprofile.update": "Actualisation du profil...",      
	  "addonprofile.parameterstool": "Paramètres de l'outil profil",
	  "addonprofile.error1": "Un maximum de 3 entités est géré dans l'outil. La couche importée en contient",
      "addonprofile.error2": "les entités sélectionnées ne sont pas de type lignes",
	  "addonprofile.error3": "Absence de sélection dans le requêteur",
	  "addonprofile.error4": "ce type de fichier ne peut être chargé",
	  "addonprofile.error5": "le traitement n'a pas retourné de données",
	  "addonprofile.fileselection": "Sélection d'un fichier gml",
	  "addonprofile.file": "Fichier",
	  "addonprofile.chart": "Graphique",
	  "addonprofile.distance": "Distance (m)",
	  "addonprofile.sources": "sources",
	  "addonprofile.elevation": "Elévation",
	  "addonprofile.inclination": "Pente",
	  "addonprofile.properties": "Caractéristiques du profil",
	  "addonprofile.referential": "Référentiel",
	  "addonprofile.totaldistance": "Distance totale",
	  "addonprofile.positivecumul": "Dénivelé positif cumulé",
	  "addonprofile.negativecumul": "Dénivelé négatif cumulé",
	  "addonprofile.csvdownload": "Télécharger au format csv",
	  "addonprofile.charttitle": "Profil en long n° ",
	  "addonprofile.drawprofile": "Tracer un profil",
	  "addonprofile.drawprofiletip":"Créer un profil en long",
	  "addonprofile.selecttoprofile": "Profil depuis sélection",
	  "addonprofile.selecttoprofiletip":"Profil depuis sélection",
	  "addonprofile.loadgml": "Charger un fichier gml.",
	  "addonprofile.loadgmltip": "Charger un fichier gml.",
	  "addonprofile.parameters": "Paramètres",
	  "addonprofile.parameterstip": "Paramètres",
	"addonprofile.processedpoints": "nb points"
	 });
OpenLayers.Util.applyDefaults(OpenLayers.Lang["en"], {    
      "addonprofile.error": "Profile tool error",
      "addonprofile.impossible": "Not possible here",	  
      "addonprofile.refresh": "Refresh",
	  "addonprofile.update": "Profile updating...",      
	  "addonprofile.parameterstool": "Profile tool parameters",
	  "addonprofile.error1": "A max of 3 features is managed in the profile tool. The imported layer contains",
      "addonprofile.error2": "Only Line geometry is managed",
	  "addonprofile.error3": "No delection in querier !",
	  "addonprofile.error4": "This file type can't be loaded",
	  "addonprofile.error5": "No data returned",
	  "addonprofile.fileselection": "gml file selection",
	  "addonprofile.file": "File",
	  "addonprofile.chart": "Chart",
	  "addonprofile.distance": "Distance (m)",
	  "addonprofile.sources": "sources",
	  "addonprofile.elevation": "Elevation",
	  "addonprofile.inclination": "Inclination",
	  "addonprofile.properties": "Profile parameters",
	  "addonprofile.referential": "Referential",
	  "addonprofile.totaldistance": "Total distance",
	  "addonprofile.positivecumul": "Dénivelé positif cumulé",
	  "addonprofile.negativecumul": "Dénivelé négatif cumulé",
	  "addonprofile.csvdownload": "Download in csv format",
	  "addonprofile.charttitle": "Profile n° ",
	  "addonprofile.drawprofile": "Draw a profile",
	  "addonprofile.drawprofiletip":"Create a new profile",
	  "addonprofile.selecttoprofile": "Selection to profile",
	  "addonprofile.selecttoprofiletip":"Selection to profile",
	  "addonprofile.loadgml": "Load gml file.",
	  "addonprofile.loadgmltip": "Load gml file.",
	  "addonprofile.parameters": "Parameters",
	  "addonprofile.parameterstip": "Parameters",  
"addonprofile.processedpoints": "nb points"      
	 });


