#!/bin/bash

chown -R jetty:jetty /var/local/geoserver
chown -R jetty:jetty /var/local/geodata

cd /var/local/geoserver

if [ -f global.xml ]
then
    echo 'Datadir already initialized'
else
    echo 'Initializing datadir from georchestra/geoserver_minimal_datadir'
    unzip /tmp/datadir.zip -d /tmp
    cp -Rax /tmp/geoserver_minimal_datadir-master/* /var/local/geoserver
fi
