name: commons CI

on:
  push:
    branches:
      - master
      - 19.04
      - 18.06

jobs:
  commons:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      #  with:
      #     submodule: recursive
      # we use this action because adding submodule: recursive to the checkout action doesn't work with
      - uses: textbook/git-checkout-submodule-action@2.0.0
      - uses: actions/setup-java@v1
        with:
          java-version: '8.x'
      - name: add georchestra artifactory to local m2 (temporary, need to move to proper action)
        run: |
          mkdir $HOME/.m2
          echo $M2_SETTINGS_FILE > $HOME/.m2/settings.xml
        env:
          M2_SETTINGS_FILE: ${{ secrets.M2_SETTINGS_FILE }}
      - name: install & check formating
        working-directory: commons/
        run: ../mvnw --no-transfer-progress -B -Dfmt.action=validate install -P-all,travis -Dadditionalparam=-Xdoclint:none -DskipTests
      - name: publish on github package repository
        working-directory: commons/
        run: ../mvnw --no-transfer-progress deploy -Dtoken=${{ secrets.GITHUB_TOKEN }}