name: Build, test and push dependencies
permissions:
  contents: read
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - '[0-9]+.[0-9]+*'
    tags:
      - '*'
  pull_request:
    paths:
      - "**"

jobs:
  build:
    if: "!startsWith(github.event.head_commit.message, '[skip ci] ')"
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: "Checking out"
        uses: actions/checkout@v6

      - name: "Setting up Java"
        uses: actions/setup-java@v5
        with:
          distribution: 'adopt'
          java-version: '21'
          cache: 'maven'
          server-id: geOrchestra-artifactory
          server-username: ARTIFACTORY_USERNAME_REF
          server-password: ARTIFACTORY_TOKEN_REF

      - name: "Installing & checking formatting"
        run: ./mvnw verify -P-all --no-transfer-progress -B -Dfmt.action=validate -DskipTests

      - name: "Publish all modules in artifactory"
        run: ./mvnw deploy -P-all --no-transfer-progress -DskipTests
        if: github.actor != 'dependabot[bot]' && github.event_name != 'pull_request'
        env:
          ARTIFACTORY_TOKEN_REF: ${{ secrets.ARTIFACTORY_TOKEN }}
          ARTIFACTORY_USERNAME_REF: ${{ secrets.ARTIFACTORY_USERNAME }}
