name: "publish geOrchestra utility jars on artifactory"
on:
  workflow_dispatch:
  tags:
  push:
    paths:
      - "testcontainers/**"
      - "security-proxy-spring-integration/**"
      - "commons/**"

permissions:
  contents: read

jobs:
  build:
    if: "!startsWith(github.event.head_commit.message, '[skip ci] ')"
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: "Checking out"
      uses: actions/checkout@v6

    - name: "Setting up Java"
      uses: actions/setup-java@v5
      with:
        distribution: 'adopt'
        java-version: '21'
        cache: 'maven'
        server-id: geOrchestra-artifactory
        server-username: ARTIFACTORY_USERNAME_REF
        server-password: ARTIFACTORY_TOKEN_REF

    - name: "building & publishing"
      run: ./mvnw verify deploy -pl :georchestra-testcontainers -pl :security-proxy-spring-integration -pl :georchestra-commons -am --no-transfer-progress -B -Dfmt.action=validate -Dadditionalparam=-Xdoclint:none
      env:
        ARTIFACTORY_TOKEN_REF: ${{ secrets.ARTIFACTORY_TOKEN }}
        ARTIFACTORY_USERNAME_REF: ${{ secrets.ARTIFACTORY_USERNAME }}
